package com.example.jainpanchang.data

import com.example.jainpanchang.data.local.DailyPanchangEntity
import com.example.jainpanchang.data.local.PanchangDao
import com.example.jainpanchang.domain.Astronomy
import com.example.jainpanchang.domain.Panchang
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.withContext
import java.time.LocalDate

class PanchangRepository(private val panchangDao: PanchangDao) {
    private val astronomy = Astronomy()
    private val panchang = Panchang(astronomy)

    suspend fun getDailyPanchang(
        date: LocalDate,
        lat: Double,
        lon: Double,
        tzOffset: Double = 5.5
    ): DailyPanchangEntity {
        val dateString = date.toString()
        val cached = panchangDao.getDailyPanchang(dateString)
        if (cached != null) {
            return cached
        }

        return withContext(Dispatchers.Default) {
            val jd = astronomy.localTimeToJd(date.year, date.monthValue, date.dayOfMonth, 0.0, tzOffset)
            val sunriseJd = astronomy.getSunrise(jd, lat, lon)
            val sunsetJd = astronomy.getSunset(jd, lat, lon)

            val sunLon = astronomy.getPlanetaryLongitude(sunriseJd, "Sun")
            val moonLon = astronomy.getPlanetaryLongitude(sunriseJd, "Moon")

            val tithiIndex = panchang.getTithi(sunLon, moonLon)
            val nakshatraIndex = panchang.getNakshatra(moonLon)
            val nakshatraPada = panchang.getNakshatraPada(moonLon)
            val yogaIndex = panchang.getYoga(sunLon, moonLon)
            val varaIndex = panchang.getVaraFromDate(date)

            // Simplistic version for demo - full port from Python requires more detailed logic (like finding exact end JDs)
            // But this covers the core elements generated by the native library!
            val entity = DailyPanchangEntity(
                dateString = dateString,
                julianDate = jd,
                sunriseJd = sunriseJd,
                sunsetJd = sunsetJd,
                tithiIndex = tithiIndex,
                tithiName = panchang.TITHI_NAMES.getOrElse(tithiIndex - 1) { "" },
                tithiEndJd = 0.0, // To be implemented with exact time calculation
                nakshatraIndex = nakshatraIndex,
                nakshatraName = panchang.NAKSHATRA_NAMES.getOrElse(nakshatraIndex - 1) { "" },
                nakshatraEndJd = 0.0,
                nakshatraPada = nakshatraPada,
                yogaIndex = yogaIndex,
                yogaName = panchang.YOGA_NAMES.getOrElse(yogaIndex - 1) { "" },
                yogaEndJd = 0.0,
                karanaIndex = 1, // Mock
                karanaName = "Bava", // Mock
                karanaStartJd = 0.0,
                karanaEndJd = 0.0,
                varaIndex = varaIndex,
                varaName = panchang.VARA_NAMES.getOrElse(varaIndex) { "" },
                hinduMonthSanskrit = panchang.getHinduMonthFromSunLon(sunLon).first,
                hinduMonthCommon = panchang.getHinduMonthFromSunLon(sunLon).second
            )

            panchangDao.insertDailyPanchang(entity)
            entity
        }
    }

    fun getPanchangForDateRange(startDate: LocalDate, endDate: LocalDate): Flow<List<DailyPanchangEntity>> {
        return panchangDao.getPanchangForDateRange(startDate.toString(), endDate.toString())
    }
}
