# jain_festival_rules.py - reviewed static rule registry for Shwetambar Jain festivals.

FESTIVAL_REGISTRY = [
    {
        "id": "mahavir_janma_kalyanak",
        "name": "Mahavir Janma Kalyanak",
        "name_hindi": "महावीर जन्म कल्याणक",
        "category": "kalyanak",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 13,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "The birthday of Lord Mahavir, the 24th Tirthankara",
        "observance": "Pujas, reading the Kalpa Sutra, and fasts. Non-Murtipujaks focus on meditation.",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "samvatsari_tapagachchha",
        "name": "Samvatsari (Tapagachchha)",
        "name_hindi": "संवत्सरी (तपगच्छ)",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha"],
        "jain_month": "Bhadrapada",
        "paksha": "Shukla",
        "tithi": 4,
        "vriddhi_rule": "second_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "The final day of Paryushan, the day of universal forgiveness",
        "observance": "Performance of Samvatsari Pratikramana, seek forgiveness with 'Micchami Dukkadam'",
        "sources": ["https://www.jainfoundation.in/JAINLIBRARY/books/Historical_Perspective_of_Samvatsari_Day_and_Jain_Calendar_200022_data.pdf"]
    },
    {
        "id": "samvatsari_sthanakvasi",
        "name": "Samvatsari (Sthanakvasi)",
        "name_hindi": "संवत्सरी (स्थानकवासी)",
        "category": "festival",
        "profiles": ["shwetambar_sthanakvasi"],
        "jain_month": "Bhadrapada",
        "paksha": "Shukla",
        "tithi": 5,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "The final day of Paryushan for Sthanakvasis, the day of universal forgiveness",
        "observance": "Meditation, chanting, Pratikramana, and 'Micchami Dukkadam'",
        "sources": ["https://www.jainfoundation.in/JAINLIBRARY/books/Historical_Perspective_of_Samvatsari_Day_and_Jain_Calendar_200022_data.pdf"]
    },
    {
        "id": "samvatsari_terapanthi",
        "name": "Samvatsari (Terapanthi)",
        "name_hindi": "संवत्सरी (तेरापंथी)",
        "category": "festival",
        "profiles": ["shwetambar_terapanthi"],
        "jain_month": "Bhadrapada",
        "paksha": "Shukla",
        "tithi": 5,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "The final day of Paryushan for Terapanthis, the day of universal forgiveness",
        "observance": "Strictly non-ritualistic meditation, fasts, and Samvatsari Pratikramana",
        "sources": ["https://www.jainfoundation.in/JAINLIBRARY/books/Historical_Perspective_of_Samvatsari_Day_and_Jain_Calendar_200022_data.pdf"]
    },
    {
        "id": "paryushan_start_tapagachchha",
        "name": "Paryushan Start (Tapagachchha)",
        "name_hindi": "पर्युषण प्रारंभ (तपगच्छ)",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha"],
        "jain_month": "Bhadrapada",
        "paksha": "Krishna",
        "tithi": 12,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Start of the 8-day Paryushan festival of self-purification",
        "observance": "Daily reading of the Kalpa Sutra, listening to discourses, and fasting",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "paryushan_start_sthanakvasi",
        "name": "Paryushan Start (Sthanakvasi)",
        "name_hindi": "पर्युषण प्रारंभ (स्थानकवासी)",
        "category": "festival",
        "profiles": ["shwetambar_sthanakvasi"],
        "jain_month": "Bhadrapada",
        "paksha": "Krishna",
        "tithi": 13,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Start of the 8-day Paryushan festival",
        "observance": "Spiritual discourses, meditation, fasting, and reading of scriptures",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "paryushan_start_terapanthi",
        "name": "Paryushan Start (Terapanthi)",
        "name_hindi": "पर्युषण प्रारंभ (तेरापंथी)",
        "category": "festival",
        "profiles": ["shwetambar_terapanthi"],
        "jain_month": "Bhadrapada",
        "paksha": "Krishna",
        "tithi": 13,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Start of the 8-day Paryushan festival",
        "observance": "Scriptural contemplation, fasting, and strict vows",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "ayambil_oli_chaitra",
        "name": "Chaitra Ayambil Oli",
        "name_hindi": "चैत्री आयंबिल ओली",
        "category": "fast",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": "7-15",
        "vriddhi_rule": "all_days",
        "kshaya_rule": "adjust_9_days",
        "adhika_rule": "nija_only",
        "meaning": "A 9-day festival of Ayambil fasts honoring the Navpad",
        "observance": "Eating only once a day of boiled grains/cereals without spice, oil, ghee, milk, or curd",
        "sources": ["https://jainpedia.org/themes/practices/festivals/ayambil-oli/"]
    },
    {
        "id": "ayambil_oli_ashvin",
        "name": "Ashvin Ayambil Oli",
        "name_hindi": "आसोज आयंबिल ओली",
        "category": "fast",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Ashwin",
        "paksha": "Shukla",
        "tithi": "7-15",
        "vriddhi_rule": "all_days",
        "kshaya_rule": "adjust_9_days",
        "adhika_rule": "nija_only",
        "meaning": "A 9-day festival of Ayambil fasts honoring the Navpad",
        "observance": "Fasting on boiled grains, performing pujas (Murtipujak) or meditation",
        "sources": ["https://www.msjs.org.au/resources/library/knowledge-base/festivals/navpadji-oli/"]
    },
    {
        "id": "diwali",
        "name": "Diwali",
        "name_hindi": "दिवाली",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Kartika",
        "paksha": "Krishna",
        "tithi": 15,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Lord Mahavir's Nirvana (Moksha) Kalyanak",
        "observance": "Lighting lamps, fasting, chanting prayers",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "jain_new_year",
        "name": "Jain New Year",
        "name_hindi": "नूतन वर्ष (वीर निर्वाण संवत)",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Kartika",
        "paksha": "Shukla",
        "tithi": 1,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Gautam Swami's Kevalgyan Kalyanak, start of VNS year",
        "observance": "Visiting temples, greeting with 'Saal Mubarak', listening to Gautam Swami's Ras",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "jnan_panchami",
        "name": "Jnan Panchami",
        "name_hindi": "ज्ञान पंचमी",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Kartika",
        "paksha": "Shukla",
        "tithi": 5,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Day of worshipping knowledge and scriptures",
        "observance": "Fasting, cleaning and worshipping religious books, performing Jnan Puja",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "dev_diwali",
        "name": "Dev Diwali",
        "name_hindi": "देव दिवाली",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Kartika",
        "paksha": "Shukla",
        "tithi": 15,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Culmination of Kartiki Chaturmas, reopening of Shatrunjay hills",
        "observance": "Illuminating temples, organizing grand pujas, and resuming pilgrimage",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "maun_ekadashi",
        "name": "Maun Agyaras",
        "name_hindi": "मौन ग्यारस",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Margashirsha",
        "paksha": "Shukla",
        "tithi": 11,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Day honoring five Kalyanakas of various Tirthankaras",
        "observance": "Maintaining complete silence (Maun), performing 150 logassa, fasting",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "parshvanath_jayanti",
        "name": "Paush Dashami",
        "name_hindi": "पोष दशमी",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Pausha",
        "paksha": "Krishna",
        "tithi": 10,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Birthday Kalyanak of Lord Parshvanath (23rd Tirthankara)",
        "observance": "Fasting, performing Paush Dashami Pujas, chanting Parshvanath prayers",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "meru_trayodashi",
        "name": "Meru Trayodashi",
        "name_hindi": "मेरु त्रयोदशी",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Magha",
        "paksha": "Krishna",
        "tithi": 13,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Lord Rishabhdev's (Adinath) Nirvana Kalyanak",
        "observance": "Worship of Mount Shatrunjay, specialized pujas and fasts",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "chaumasi_chaudas_ashadha",
        "name": "Ashadha Chaumasi Chaudas",
        "name_hindi": "आषाढी चौमासी चौदश",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Ashadha",
        "paksha": "Shukla",
        "tithi": 14,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Start of the holy Chaturmas period",
        "observance": "Fasting, starting Chaturmas vows, and performing special Pratikramana",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "chaumasi_chaudas_kartika",
        "name": "Kartika Chaumasi Chaudas",
        "name_hindi": "कार्तिकी चौमासी चौदश",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Kartika",
        "paksha": "Shukla",
        "tithi": 14,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "End of the main Chaturmas period",
        "observance": "Performing grand Chaumasi Pratikramana, concluding monsoon vows",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "chaumasi_chaudas_phalguna",
        "name": "Phalguna Chaumasi Chaudas",
        "name_hindi": "फाल्गुनी चौमासी चौदश",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Phalguna",
        "paksha": "Shukla",
        "tithi": 14,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Third Chaumasi Chaudas of the year",
        "observance": "Spiritual cleansing, fasting, and performing Chaumasi Pratikramana",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    # Recurring Parva Tithis
    {
        "id": "pakhi_chaudas_shukla",
        "name": "Pakhi Chaudas (Shukla)",
        "name_hindi": "पाखी चौदश (शुक्ल)",
        "category": "parva",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": None,
        "paksha": "Shukla",
        "tithi": 14,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Bi-weekly day of spiritual purification and fasting",
        "observance": "Performance of Pakshik Pratikramana and observing dietary restrictions",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "pakhi_chaudas_krishna",
        "name": "Pakhi Chaudas (Krishna)",
        "name_hindi": "पाखी चौदश (कृष्ण)",
        "category": "parva",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": None,
        "paksha": "Krishna",
        "tithi": 14,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Bi-weekly day of spiritual purification and fasting",
        "observance": "Performance of Pakshik Pratikramana and observing dietary restrictions",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "parva_tithi_ashtami_shukla",
        "name": "Parva Tithi (Shukla Ashtami)",
        "name_hindi": "पर्व तिथि (शुक्ल अष्टमी)",
        "category": "parva",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": None,
        "paksha": "Shukla",
        "tithi": 8,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Fortnightly holy day for fasting and penance",
        "observance": "Observing abstinences, avoiding green vegetables, performing Samayik",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "parva_tithi_ashtami_krishna",
        "name": "Parva Tithi (Krishna Ashtami)",
        "name_hindi": "पर्व तिथि (कृष्ण अष्टमी)",
        "category": "parva",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": None,
        "paksha": "Krishna",
        "tithi": 8,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Fortnightly holy day for fasting and penance",
        "observance": "Avoiding green/root vegetables, engaging in scripture study",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "parva_tithi_purnima",
        "name": "Parva Tithi (Purnima)",
        "name_hindi": "पर्व तिथि (पूर्णिमा)",
        "category": "parva",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": None,
        "paksha": "Shukla",
        "tithi": 15,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Monthly full moon spiritual day",
        "observance": "Temple visits, special prayers, and charitable donations",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "parva_tithi_amavasya",
        "name": "Parva Tithi (Amavasya)",
        "name_hindi": "पर्व तिथि (अमावस्या)",
        "category": "parva",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": None,
        "paksha": "Krishna",
        "tithi": 15,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Monthly new moon spiritual day",
        "observance": "Inner contemplation, fasting, and offering prayers",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    }
]
