# jain_festival_rules.py - reviewed static rule registry for Shwetambar Jain festivals.

FESTIVAL_REGISTRY = [
    {
        "id": "mahavir_janma_kalyanak",
        "name": "Mahavir Janma Kalyanak",
        "name_gujarati": "મહાવીર જન્મ કલ્યાણક",
        "category": "kalyanak",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 13,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "The birthday of Lord Mahavir, the 24th Tirthankara",
        "observance": "Pujas, reading the Kalpa Sutra, and fasts. Non-Murtipujaks focus on meditation.",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "samvatsari_tapagachchha",
        "name": "Samvatsari (Tapagachchha)",
        "name_gujarati": "સંવત્સરી (તપગચ્છ)",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha"],
        "jain_month": "Bhadrapada",
        "paksha": "Shukla",
        "tithi": 4,
        "vriddhi_rule": "second_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "The final day of Paryushan, the day of universal forgiveness",
        "observance": "Performance of Samvatsari Pratikramana, seek forgiveness with 'Micchami Dukkadam'",
        "sources": ["https://www.jainfoundation.in/JAINLIBRARY/books/Historical_Perspective_of_Samvatsari_Day_and_Jain_Calendar_200022_data.pdf"]
    },
    {
        "id": "samvatsari_sthanakvasi",
        "name": "Samvatsari (Sthanakvasi)",
        "name_gujarati": "સંવત્સરી (સ્થાનકવાસી)",
        "category": "festival",
        "profiles": ["shwetambar_sthanakvasi"],
        "jain_month": "Bhadrapada",
        "paksha": "Shukla",
        "tithi": 5,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "The final day of Paryushan for Sthanakvasis, the day of universal forgiveness",
        "observance": "Meditation, chanting, Pratikramana, and 'Micchami Dukkadam'",
        "sources": ["https://www.jainfoundation.in/JAINLIBRARY/books/Historical_Perspective_of_Samvatsari_Day_and_Jain_Calendar_200022_data.pdf"]
    },
    {
        "id": "samvatsari_terapanthi",
        "name": "Samvatsari (Terapanthi)",
        "name_gujarati": "સંવત્સરી (તેરાપંથી)",
        "category": "festival",
        "profiles": ["shwetambar_terapanthi"],
        "jain_month": "Bhadrapada",
        "paksha": "Shukla",
        "tithi": 5,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "The final day of Paryushan for Terapanthis, the day of universal forgiveness",
        "observance": "Strictly non-ritualistic meditation, fasts, and Samvatsari Pratikramana",
        "sources": ["https://www.jainfoundation.in/JAINLIBRARY/books/Historical_Perspective_of_Samvatsari_Day_and_Jain_Calendar_200022_data.pdf"]
    },
    {
        "id": "paryushan_start_tapagachchha",
        "name": "Paryushan Start (Tapagachchha)",
        "name_gujarati": "પર્યુષણ પ્રારંભ (તપગચ્છ)",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha"],
        "jain_month": "Bhadrapada",
        "paksha": "Krishna",
        "tithi": 12,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Start of the 8-day Paryushan festival of self-purification",
        "observance": "Daily reading of the Kalpa Sutra, listening to discourses, and fasting",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "paryushan_start_sthanakvasi",
        "name": "Paryushan Start (Sthanakvasi)",
        "name_gujarati": "પર્યુષણ પ્રારંભ (સ્થાનકવાસી)",
        "category": "festival",
        "profiles": ["shwetambar_sthanakvasi"],
        "jain_month": "Bhadrapada",
        "paksha": "Krishna",
        "tithi": 13,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Start of the 8-day Paryushan festival",
        "observance": "Spiritual discourses, meditation, fasting, and reading of scriptures",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "paryushan_start_terapanthi",
        "name": "Paryushan Start (Terapanthi)",
        "name_gujarati": "પર્યુષણ પ્રારંભ (તેરાપંથી)",
        "category": "festival",
        "profiles": ["shwetambar_terapanthi"],
        "jain_month": "Bhadrapada",
        "paksha": "Krishna",
        "tithi": 13,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Start of the 8-day Paryushan festival",
        "observance": "Scriptural contemplation, fasting, and strict vows",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "ayambil_oli_chaitra",
        "name": "Chaitra Ayambil Oli",
        "name_gujarati": "ચૈત્રી આયંબિલ ઓળી",
        "category": "fast",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": "7-15",
        "vriddhi_rule": "all_days",
        "kshaya_rule": "adjust_9_days",
        "adhika_rule": "nija_only",
        "meaning": "A 9-day festival of Ayambil fasts honoring the Navpad",
        "observance": "Eating only once a day of boiled grains/cereals without spice, oil, ghee, milk, or curd",
        "sources": ["https://jainpedia.org/themes/practices/festivals/ayambil-oli/"]
    },
    {
        "id": "ayambil_oli_ashvin",
        "name": "Ashvin Ayambil Oli",
        "name_gujarati": "આસોજી આયંબિલ ઓળી",
        "category": "fast",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Ashwin",
        "paksha": "Shukla",
        "tithi": "7-15",
        "vriddhi_rule": "all_days",
        "kshaya_rule": "adjust_9_days",
        "adhika_rule": "nija_only",
        "meaning": "A 9-day festival of Ayambil fasts honoring the Navpad",
        "observance": "Fasting on boiled grains, performing pujas (Murtipujak) or meditation",
        "sources": ["https://www.msjs.org.au/resources/library/knowledge-base/festivals/navpadji-oli/"]
    },
    {
        "id": "diwali",
        "name": "Diwali",
        "name_gujarati": "દિવાળી",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Kartika",
        "paksha": "Krishna",
        "tithi": 30,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Lord Mahavir's Nirvana (Moksha) Kalyanak",
        "observance": "Lighting lamps, fasting, chanting prayers",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "jain_new_year",
        "name": "Jain New Year",
        "name_gujarati": "નૂતન વર્ષ (વીર નિર્વાણ સંવત)",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Kartika",
        "paksha": "Shukla",
        "tithi": 1,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Gautam Swami's Kevalgyan Kalyanak, start of VNS year",
        "observance": "Visiting temples, greeting with 'Saal Mubarak', listening to Gautam Swami's Ras",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "jnan_panchami",
        "name": "Jnan Panchami",
        "name_gujarati": "જ્ઞાન પંચમી",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Kartika",
        "paksha": "Shukla",
        "tithi": 5,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Day of worshipping knowledge and scriptures",
        "observance": "Fasting, cleaning and worshipping religious books, performing Jnan Puja",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "dev_diwali",
        "name": "Dev Diwali",
        "name_gujarati": "દેવ દિવાળી",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Kartika",
        "paksha": "Shukla",
        "tithi": 15,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Culmination of Kartiki Chaturmas, reopening of Shatrunjay hills",
        "observance": "Illuminating temples, organizing grand pujas, and resuming pilgrimage",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "maun_ekadashi",
        "name": "Maun Agyaras",
        "name_gujarati": "મૌન અગિયારસ",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Margashirsha",
        "paksha": "Shukla",
        "tithi": 11,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Day honoring five Kalyanakas of various Tirthankaras",
        "observance": "Maintaining complete silence (Maun), performing 150 logassa, fasting",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "parshvanath_jayanti",
        "name": "Paush Dashami",
        "name_gujarati": "પોષ દશમી",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Pausha",
        "paksha": "Krishna",
        "tithi": 25,  # 1-indexed Amanta: Krishna 10 is Tithi 25
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Birthday Kalyanak of Lord Parshvanath (23rd Tirthankara)",
        "observance": "Fasting, performing Paush Dashami Pujas, chanting Parshvanath prayers",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "meru_trayodashi",
        "name": "Meru Trayodashi",
        "name_gujarati": "મેરુ ત્રયોદશી",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Magha",
        "paksha": "Krishna",
        "tithi": 28,  # 1-indexed Amanta: Krishna 13 is Tithi 28
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Lord Rishabhdev's (Adinath) Nirvana Kalyanak",
        "observance": "Worship of Mount Shatrunjay, specialized pujas and fasts",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "chaumasi_chaudas_ashadha",
        "name": "Ashadha Chaumasi Chaudas",
        "name_gujarati": "અષાઢી ચૌમાસી ચૌદશ",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Ashadha",
        "paksha": "Shukla",
        "tithi": 14,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Start of the holy Chaturmas period",
        "observance": "Fasting, starting Chaturmas vows, and performing special Pratikramana",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "chaumasi_chaudas_kartika",
        "name": "Kartika Chaumasi Chaudas",
        "name_gujarati": "કાર્તિકી ચૌમાસી ચૌદશ",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Kartika",
        "paksha": "Shukla",
        "tithi": 14,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "End of the main Chaturmas period",
        "observance": "Performing grand Chaumasi Pratikramana, concluding monsoon vows",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "chaumasi_chaudas_phalguna",
        "name": "Phalguna Chaumasi Chaudas",
        "name_gujarati": "ફાલ્ગુની ચૌમાસી ચૌદશ",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": "Phalguna",
        "paksha": "Shukla",
        "tithi": 14,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Third Chaumasi Chaudas of the year",
        "observance": "Spiritual cleansing, fasting, and performing Chaumasi Pratikramana",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    # Recurring Parva Tithis
    {
        "id": "pakhi_chaudas_shukla",
        "name": "Pakhi Chaudas (Shukla)",
        "name_gujarati": "પાખી ચૌદશ (શુક્લ)",
        "category": "parva",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": None,
        "paksha": "Shukla",
        "tithi": 14,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Bi-weekly day of spiritual purification and fasting",
        "observance": "Performance of Pakshik Pratikramana and observing dietary restrictions",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "pakhi_chaudas_krishna",
        "name": "Pakhi Chaudas (Krishna)",
        "name_gujarati": "પાખી ચૌદશ (કૃષ્ણ)",
        "category": "parva",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": None,
        "paksha": "Krishna",
        "tithi": 29,  # Tithi index 29 (Krishna 14)
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Bi-weekly day of spiritual purification and fasting",
        "observance": "Performance of Pakshik Pratikramana and observing dietary restrictions",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "parva_tithi_ashtami_shukla",
        "name": "Parva Tithi (Shukla Ashtami)",
        "name_gujarati": "પર્વ તિથિ (શુક્લ અષ્ટમી)",
        "category": "parva",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": None,
        "paksha": "Shukla",
        "tithi": 8,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Fortnightly holy day for fasting and penance",
        "observance": "Observing abstinences, avoiding green vegetables, performing Samayik",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "parva_tithi_ashtami_krishna",
        "name": "Parva Tithi (Krishna Ashtami)",
        "name_gujarati": "પર્વ તિથિ (કૃષ્ણ અષ્ટમી)",
        "category": "parva",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": None,
        "paksha": "Krishna",
        "tithi": 23,  # Tithi index 23 (Krishna 8)
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Fortnightly holy day for fasting and penance",
        "observance": "Avoiding green/root vegetables, engaging in scripture study",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "parva_tithi_purnima",
        "name": "Parva Tithi (Purnima)",
        "name_gujarati": "પર્વ તિથિ (પૂનમ)",
        "category": "parva",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": None,
        "paksha": "Shukla",
        "tithi": 15,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Monthly full moon spiritual day",
        "observance": "Temple visits, special prayers, and charitable donations",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    },
    {
        "id": "parva_tithi_amavasya",
        "name": "Parva Tithi (Amavasya)",
        "name_gujarati": "પર્વ તિથિ (અમાસ)",
        "category": "parva",
        "profiles": ["shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "jain_month": None,
        "paksha": "Krishna",
        "tithi": 30,
        "vriddhi_rule": "first_day",
        "kshaya_rule": "next_day",
        "adhika_rule": "nija_only",
        "meaning": "Monthly new moon spiritual day",
        "observance": "Inner contemplation, fasting, and offering prayers",
        "sources": ["https://jainpedia.org/themes/practices/festivals/"]
    }
]
