# -*- coding: utf-8 -*-

FESTIVAL_REGISTRY = [
    {
        "id": "shri_mahavir_swami_ji___moksha_kalyanak__the_nirvana_liberation_of_lord_mahavira__celebrated_as_jain_diwali",
        "name": "Shri Mahavir Swami Ji - Moksha Kalyanak (The Nirvana/Liberation of Lord Mahavira, celebrated as Jain Diwali).",
        "category": "festival",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashwin",
        "paksha": "Krishna",
        "tithi": 15,
    },
    {
        "id": "diwali",
        "name": "Diwali (Mahavir Nirvan & Gautam Swami Kevalgyan)",
        "name_hindi": "दीपावली (भगवान महावीर निर्वाण)",
        "category": "festival",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Kartik",
        "paksha": "Krishna",
        "tithi": 15,
        "meaning": "Moksha of Bhagwan Mahavir and Kevalgyan of Gautam Swami",
        "observance": "Laddoo offering & Swadhyay",
        "sources": ["Jain Traditions"],
    },
    {
        "id": "meru_trayodashi",
        "name": "Meru Trayodashi",
        "name_hindi": "मेरु त्रयोदशी",
        "category": "festival",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Krishna",
        "tithi": 13,
        "meaning": "Nirvan of Bhagwan Rishabhdev (Adinath)",
        "observance": "Fasting and Prayer",
        "sources": ["Jain Traditions"],
    },
    {
        "id": "samvatsari_tapagachchha",
        "name": "Samvatsari (Tapagachchha)",
        "name_hindi": "संवत्सरी (तपागच्छ)",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha"],
        "rule_type": "SingleTithi",
        "jain_month": "Bhadrapada",
        "paksha": "Shukla",
        "tithi": 4,
        "vriddhi_rule": "second_day",
        "meaning": "Samvatsari Mahaparva",
        "observance": "Kshamapana & Upvas",
        "sources": ["Tapagachchha Rules"],
    },
    {
        "id": "samvatsari_sthanakvasi",
        "name": "Samvatsari (Sthanakvasi / Terapanthi)",
        "name_hindi": "संवत्सरी (स्थानकवासी/तेरापंथी)",
        "category": "festival",
        "profiles": ["shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "rule_type": "SingleTithi",
        "jain_month": "Bhadrapada",
        "paksha": "Shukla",
        "tithi": 5,
        "vriddhi_rule": "second_day",
        "meaning": "Samvatsari Mahaparva",
        "observance": "Kshamapana & Upvas",
        "sources": ["Sthanakvasi Rules"],
    },
    {
        "id": "parva_tithi_amavasya",
        "name": "Parva Tithi - Amavasya",
        "name_hindi": "अमावस्या पर्व तिथि",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "paksha": "Krishna",
        "tithi": 15,
        "meaning": "Monthly Amavasya Parva Tithi",
        "observance": "Special prayer and self-study",
        "sources": ["Jain Panchang Rules"],
    },
    {
        "id": "parva_tithi_purnima",
        "name": "Parva Tithi - Purnima",
        "name_hindi": "पूर्णिमा पर्व तिथि",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "paksha": "Shukla",
        "tithi": 15,
        "meaning": "Monthly Purnima Parva Tithi",
        "observance": "Special prayer and self-study",
        "sources": ["Jain Panchang Rules"],
    },
    {
        "id": "parva_tithi_ashtami_krishna",
        "name": "Parva Tithi - Krishna Ashtami",
        "name_hindi": "कृष्ण अष्टमी पर्व तिथि",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "paksha": "Krishna",
        "tithi": 8,
        "meaning": "Monthly Krishna Ashtami Parva Tithi",
        "observance": "Fasting / Swadhyay",
        "sources": ["Jain Panchang Rules"],
    },
    {
        "id": "parva_tithi_ashtami_shukla",
        "name": "Parva Tithi - Shukla Ashtami",
        "name_hindi": "शुक्ल अष्टमी पर्व तिथि",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "paksha": "Shukla",
        "tithi": 8,
        "meaning": "Monthly Shukla Ashtami Parva Tithi",
        "observance": "Fasting / Swadhyay",
        "sources": ["Jain Panchang Rules"],
    },
    {
        "id": "pakhi_chaudas_ashadha",
        "name": "Pakhi Chaudas - Shukla Chaturdashi",
        "name_hindi": "पाखी चौदस (शुक्ल चतुर्दशी)",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashadha",
        "paksha": "Shukla",
        "tithi": 14,
        "meaning": "Chaturmas Pakhi Chaudas",
        "observance": "Pakshik Pratikraman",
        "sources": ["Jain Panchang Rules"],
    },
    {
        "id": "pakhi_chaudas_shravana",
        "name": "Pakhi Chaudas - Shukla Chaturdashi",
        "name_hindi": "पाखी चौदस (शुक्ल चतुर्दशी)",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Shravana",
        "paksha": "Shukla",
        "tithi": 14,
        "meaning": "Chaturmas Pakhi Chaudas",
        "observance": "Pakshik Pratikraman",
        "sources": ["Jain Panchang Rules"],
    },
    {
        "id": "pakhi_chaudas_bhadrapada",
        "name": "Pakhi Chaudas - Shukla Chaturdashi",
        "name_hindi": "पाखी चौदस (शुक्ल चतुर्दशी)",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Bhadrapada",
        "paksha": "Shukla",
        "tithi": 14,
        "meaning": "Chaturmas Pakhi Chaudas",
        "observance": "Pakshik Pratikraman",
        "sources": ["Jain Panchang Rules"],
    },
    {
        "id": "pakhi_chaudas_ashwin",
        "name": "Pakhi Chaudas - Shukla Chaturdashi",
        "name_hindi": "पाखी चौदस (शुक्ल चतुर्दशी)",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashwin",
        "paksha": "Shukla",
        "tithi": 14,
        "meaning": "Chaturmas Pakhi Chaudas",
        "observance": "Pakshik Pratikraman",
        "sources": ["Jain Panchang Rules"],
    },
    {
        "id": "jyeshtha_jinvar_vrat_begins",
        "name": "Jyeshtha Jinvar Vrat Begins",
        "name_hindi": "ज्येष्ठ जिनवर व्रत प्रारंभ",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Krishna",
        "tithi": 1,
        "meaning": "Start of Jyeshtha Jinvar Vrat",
        "observance": "Fasting and worship",
        "sources": ["Jain Panchang Rules"],
    },
    {
        "id": "shrut_panchami",
        "name": "Shrut Panchami (Jinvani Divas)",
        "name_hindi": "श्रुत पंचमी (जिनवाणी दिवस)",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Shukla",
        "tithi": 5,
        "meaning": "Worship of the first written Jain scriptures",
        "observance": "Jinvani Puja, Swadhyay",
        "sources": ["Jain Panchang Rules"],
    },
    {
        "id": "veera_shasana_jayanti",
        "name": "Veera Shasana Jayanti",
        "name_hindi": "वीर शासन जयंती",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashadha",
        "paksha": "Krishna",
        "tithi": 1,
        "meaning": "Commemorates Lord Mahavira's first divine sermon (Divya Dhwani)",
        "observance": "Worship, discourses, and celebration",
        "sources": ["Jain Panchang Rules"],
    },
    {
        "id": "raksha_bandhan",
        "name": "Raksha Bandhan (Vishnukumar Muni Parv)",
        "name_hindi": "रक्षाबंधन (विष्णुकुमार मुनि पर्व)",
        "category": "mahaparv",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Shravana",
        "paksha": "Shukla",
        "tithi": 15,
        "meaning": "Commemorates Muni Vishnukumar protecting 700 Jain ascetics",
        "observance": "Worship, community gathering",
        "sources": ["Jain Panchang Rules"],
    },
    {
        "id": "navpad_ayambil_oli_autumn",
        "name": "Oli Fasting Begins (Navpad Ayambil Oli)",
        "name_hindi": "ओली प्रारंभ (नवपद आयम्बिल ओली)",
        "category": "mahaparv",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashwin",
        "paksha": "Shukla",
        "tithi": 15,
        "meaning": "Beginning of the 9-day Autumn Navpad Ayambil Oli fast.",
        "observance": "Ayambil fast for 9 days, meditating on the Navpad.",
        "sources": ["Jain Panchang Rules"],
    },
    {
        "id": "mahavir_nirvana_deepavali",
        "name": "Mahavir Swami Nirvana Kalyanak (Deepavali)",
        "name_hindi": "महावीर स्वामी निर्वाण कल्याणक (दीपावली)",
        "category": "mahaparv",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashwin",
        "paksha": "Krishna",
        "tithi": 15,
        "meaning": "Bhagwan Mahavira attained Nirvana (liberation) at Pavapuri.",
        "observance": "Lighting of lamps, offering of Nirvan Ladoo.",
        "sources": ["Jain Panchang Rules"],
    },
    {
        "id": "navpad_ayambil_oli_spring",
        "name": "Oli Fasting Begins (Navpad Ayambil Oli)",
        "name_hindi": "ओली प्रारंभ (नवपद आयम्बिल ओली)",
        "category": "mahaparv",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 9,
        "meaning": "Beginning of the 9-day Spring Navpad Ayambil Oli fast.",
        "observance": "Ayambil fast for 9 days, meditating on the Navpad.",
        "sources": ["Jain Panchang Rules"],
    },
    {
        "id": "shri_parshvanath_ji___omniscience_kalyanak_4_vrindavan_ashadhara",
        "name": "Shri Parshvanath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Krishna",
        "tithi": 4,
        "meaning": "Omniscience Kalyanak of Lord Parshvanath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Ashadhara"],
    },
    {
        "id": "shri_parshvanath_ji___omniscience_kalyanak_14_uttarapurana",
        "name": "Shri Parshvanath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Krishna",
        "tithi": 14,
        "meaning": "Omniscience Kalyanak of Lord Parshvanath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Uttarapurana"],
    },
    {
        "id": "shri_chandraprabha_ji___conception_kalyanak_5_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Chandraprabha Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Krishna",
        "tithi": 5,
        "meaning": "Conception Kalyanak of Lord Chandraprabha",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_sheetalnath_ji___conception_kalyanak_8_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Sheetalnath Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Krishna",
        "tithi": 8,
        "meaning": "Conception Kalyanak of Lord Sheetalnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_rishabhdev_ji___austerity_kalyanak_9_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Rishabhdev (Adinath) Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Krishna",
        "tithi": 9,
        "meaning": "Austerity Kalyanak of Lord Rishabhdev (Adinath)",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_rishabhdev_ji___birth_kalyanak_9_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Rishabhdev (Adinath) Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Krishna",
        "tithi": 9,
        "meaning": "Birth Kalyanak of Lord Rishabhdev (Adinath)",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_anantnath_ji___liberation_kalyanak_15_vrindavan_ashadhara",
        "name": "Shri Anantnath Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Krishna",
        "tithi": 15,
        "meaning": "Liberation Kalyanak of Lord Anantnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Ashadhara"],
    },
    {
        "id": "shri_anantnath_ji___liberation_kalyanak_15_uttarapurana",
        "name": "Shri Anantnath Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Krishna",
        "tithi": 15,
        "meaning": "Liberation Kalyanak of Lord Anantnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Uttarapurana"],
    },
    {
        "id": "shri_anantnath_ji___omniscience_kalyanak_15_vrindavan_ashadhara",
        "name": "Shri Anantnath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Krishna",
        "tithi": 15,
        "meaning": "Omniscience Kalyanak of Lord Anantnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Ashadhara"],
    },
    {
        "id": "shri_anantnath_ji___omniscience_kalyanak_15_uttarapurana",
        "name": "Shri Anantnath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Krishna",
        "tithi": 15,
        "meaning": "Omniscience Kalyanak of Lord Anantnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Uttarapurana"],
    },
    {
        "id": "shri_arahnath_ji___liberation_kalyanak_15_vrindavan_ashadhara",
        "name": "Shri Arahnath Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Krishna",
        "tithi": 15,
        "meaning": "Liberation Kalyanak of Lord Arahnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Ashadhara"],
    },
    {
        "id": "shri_arahnath_ji___liberation_kalyanak_15_uttarapurana",
        "name": "Shri Arahnath Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Krishna",
        "tithi": 15,
        "meaning": "Liberation Kalyanak of Lord Arahnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Uttarapurana"],
    },
    {
        "id": "shri_mallinath_ji___conception_kalyanak_1_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Mallinath Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 1,
        "meaning": "Conception Kalyanak of Lord Mallinath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_kunthunath_ji___omniscience_kalyanak_3_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Kunthunath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 3,
        "meaning": "Omniscience Kalyanak of Lord Kunthunath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_ajitnath_ji___liberation_kalyanak_5_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Ajitnath Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 5,
        "meaning": "Liberation Kalyanak of Lord Ajitnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_sambhavnath_ji___liberation_kalyanak_6_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Sambhavnath Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 6,
        "meaning": "Liberation Kalyanak of Lord Sambhavnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_padmaprabha_ji___liberation_kalyanak_9_vrindavan",
        "name": "Shri Padmaprabha Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 9,
        "meaning": "Liberation Kalyanak of Lord Padmaprabha",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan"],
    },
    {
        "id": "shri_sumatinath_ji___birth_kalyanak_11_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Sumatinath Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 11,
        "meaning": "Birth Kalyanak of Lord Sumatinath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_sumatinath_ji___liberation_kalyanak_11_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Sumatinath Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 11,
        "meaning": "Liberation Kalyanak of Lord Sumatinath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_sumatinath_ji___omniscience_kalyanak_11_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Sumatinath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 11,
        "meaning": "Omniscience Kalyanak of Lord Sumatinath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_mahavira_ji___birth_kalyanak_13_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Mahavira Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 13,
        "meaning": "Birth Kalyanak of Lord Mahavira",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_padmaprabha_ji___omniscience_kalyanak_15_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Padmaprabha Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 15,
        "meaning": "Omniscience Kalyanak of Lord Padmaprabha",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_parshvanath_ji___conception_kalyanak_2_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Parshvanath Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Krishna",
        "tithi": 2,
        "meaning": "Conception Kalyanak of Lord Parshvanath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_munisuvrat_ji___omniscience_kalyanak_9_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Munisuvrat Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Krishna",
        "tithi": 9,
        "meaning": "Omniscience Kalyanak of Lord Munisuvrat",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_munisuvrat_ji___austerity_kalyanak_10_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Munisuvrat Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Krishna",
        "tithi": 10,
        "meaning": "Austerity Kalyanak of Lord Munisuvrat",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_munisuvrat_ji___birth_kalyanak_10_vrindavan_ashadhara",
        "name": "Shri Munisuvrat Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Krishna",
        "tithi": 10,
        "meaning": "Birth Kalyanak of Lord Munisuvrat",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Ashadhara"],
    },
    {
        "id": "shri_munisuvrat_ji___birth_kalyanak_12_uttarapurana",
        "name": "Shri Munisuvrat Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Krishna",
        "tithi": 12,
        "meaning": "Birth Kalyanak of Lord Munisuvrat",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Uttarapurana"],
    },
    {
        "id": "shri_dharmanath_ji___conception_kalyanak_13_ashadhara",
        "name": "Shri Dharmanath Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Krishna",
        "tithi": 13,
        "meaning": "Conception Kalyanak of Lord Dharmanath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Ashadhara"],
    },
    {
        "id": "shri_naminath_ji___liberation_kalyanak_14_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Naminath Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Krishna",
        "tithi": 14,
        "meaning": "Liberation Kalyanak of Lord Naminath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_kunthunath_ji___austerity_kalyanak_1_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Kunthunath Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Shukla",
        "tithi": 1,
        "meaning": "Austerity Kalyanak of Lord Kunthunath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_kunthunath_ji___birth_kalyanak_1_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Kunthunath Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Shukla",
        "tithi": 1,
        "meaning": "Birth Kalyanak of Lord Kunthunath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_kunthunath_ji___liberation_kalyanak_1_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Kunthunath Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Shukla",
        "tithi": 1,
        "meaning": "Liberation Kalyanak of Lord Kunthunath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_abhinandan_ji___conception_kalyanak_6_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Abhinandan Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Shukla",
        "tithi": 6,
        "meaning": "Conception Kalyanak of Lord Abhinandan",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_abhinandan_ji___liberation_kalyanak_6_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Abhinandan Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Shukla",
        "tithi": 6,
        "meaning": "Liberation Kalyanak of Lord Abhinandan",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_dharmanath_ji___conception_kalyanak_8_vrindavan",
        "name": "Shri Dharmanath Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Shukla",
        "tithi": 8,
        "meaning": "Conception Kalyanak of Lord Dharmanath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan"],
    },
    {
        "id": "shri_dharmanath_ji___conception_kalyanak_13_uttarapurana",
        "name": "Shri Dharmanath Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Shukla",
        "tithi": 13,
        "meaning": "Conception Kalyanak of Lord Dharmanath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Uttarapurana"],
    },
    {
        "id": "shri_sumatinath_ji___austerity_kalyanak_9_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Sumatinath Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Shukla",
        "tithi": 9,
        "meaning": "Austerity Kalyanak of Lord Sumatinath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_mahavira_ji___omniscience_kalyanak_10_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Mahavira Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Shukla",
        "tithi": 10,
        "meaning": "Omniscience Kalyanak of Lord Mahavira",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_shreyansnath_ji___conception_kalyanak_6_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Shreyansnath Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Krishna",
        "tithi": 6,
        "meaning": "Conception Kalyanak of Lord Shreyansnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_vimalnath_ji___conception_kalyanak_10_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Vimalnath Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Krishna",
        "tithi": 10,
        "meaning": "Conception Kalyanak of Lord Vimalnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_anantnath_ji___austerity_kalyanak_12_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Anantnath Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Krishna",
        "tithi": 12,
        "meaning": "Austerity Kalyanak of Lord Anantnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_anantnath_ji___birth_kalyanak_12_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Anantnath Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Krishna",
        "tithi": 12,
        "meaning": "Birth Kalyanak of Lord Anantnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_shantinath_ji___austerity_kalyanak_14_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Shantinath Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Krishna",
        "tithi": 14,
        "meaning": "Austerity Kalyanak of Lord Shantinath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_shantinath_ji___birth_kalyanak_14_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Shantinath Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Krishna",
        "tithi": 14,
        "meaning": "Birth Kalyanak of Lord Shantinath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_shantinath_ji___liberation_kalyanak_14_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Shantinath Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Krishna",
        "tithi": 14,
        "meaning": "Liberation Kalyanak of Lord Shantinath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_ajitnath_ji___conception_kalyanak_15_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Ajitnath Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Krishna",
        "tithi": 15,
        "meaning": "Conception Kalyanak of Lord Ajitnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_dharmanath_ji___liberation_kalyanak_4_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Dharmanath Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Shukla",
        "tithi": 4,
        "meaning": "Liberation Kalyanak of Lord Dharmanath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_suparshvanath_ji___austerity_kalyanak_12_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Suparshvanath Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Shukla",
        "tithi": 12,
        "meaning": "Austerity Kalyanak of Lord Suparshvanath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_suparshvanath_ji___birth_kalyanak_12_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Suparshvanath Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Shukla",
        "tithi": 12,
        "meaning": "Birth Kalyanak of Lord Suparshvanath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_rishabhdev_ji___conception_kalyanak_2_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Rishabhdev (Adinath) Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashadha",
        "paksha": "Krishna",
        "tithi": 2,
        "meaning": "Conception Kalyanak of Lord Rishabhdev (Adinath)",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_vasupujya_ji___conception_kalyanak_6_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Vasupujya Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashadha",
        "paksha": "Krishna",
        "tithi": 6,
        "meaning": "Conception Kalyanak of Lord Vasupujya",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_vimalnath_ji___liberation_kalyanak_6_vrindavan",
        "name": "Shri Vimalnath Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashadha",
        "paksha": "Krishna",
        "tithi": 6,
        "meaning": "Liberation Kalyanak of Lord Vimalnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan"],
    },
    {
        "id": "shri_vimalnath_ji___liberation_kalyanak_8_uttarapurana_ashadhara",
        "name": "Shri Vimalnath Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashadha",
        "paksha": "Krishna",
        "tithi": 8,
        "meaning": "Liberation Kalyanak of Lord Vimalnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_naminath_ji___austerity_kalyanak_10_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Naminath Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashadha",
        "paksha": "Krishna",
        "tithi": 10,
        "meaning": "Austerity Kalyanak of Lord Naminath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_naminath_ji___birth_kalyanak_10_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Naminath Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashadha",
        "paksha": "Krishna",
        "tithi": 10,
        "meaning": "Birth Kalyanak of Lord Naminath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_mahavira_ji___conception_kalyanak_6_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Mahavira Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashadha",
        "paksha": "Shukla",
        "tithi": 6,
        "meaning": "Conception Kalyanak of Lord Mahavira",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_neminath_ji___liberation_kalyanak_7_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Neminath Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashadha",
        "paksha": "Shukla",
        "tithi": 7,
        "meaning": "Liberation Kalyanak of Lord Neminath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_munisuvrat_ji___conception_kalyanak_2_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Munisuvrat Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Shravana",
        "paksha": "Krishna",
        "tithi": 2,
        "meaning": "Conception Kalyanak of Lord Munisuvrat",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_kunthunath_ji___conception_kalyanak_10_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Kunthunath Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Shravana",
        "paksha": "Krishna",
        "tithi": 10,
        "meaning": "Conception Kalyanak of Lord Kunthunath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_sumatinath_ji___conception_kalyanak_2_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Sumatinath Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Shravana",
        "paksha": "Shukla",
        "tithi": 2,
        "meaning": "Conception Kalyanak of Lord Sumatinath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_neminath_ji___austerity_kalyanak_6_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Neminath Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Shravana",
        "paksha": "Shukla",
        "tithi": 6,
        "meaning": "Austerity Kalyanak of Lord Neminath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_neminath_ji___birth_kalyanak_6_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Neminath Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Shravana",
        "paksha": "Shukla",
        "tithi": 6,
        "meaning": "Birth Kalyanak of Lord Neminath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_parshvanath_ji___liberation_kalyanak_7_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Parshvanath Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Shravana",
        "paksha": "Shukla",
        "tithi": 7,
        "meaning": "Liberation Kalyanak of Lord Parshvanath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_shreyansnath_ji___liberation_kalyanak_15_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Shreyansnath Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Shravana",
        "paksha": "Shukla",
        "tithi": 15,
        "meaning": "Liberation Kalyanak of Lord Shreyansnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_shantinath_ji___conception_kalyanak_7_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Shantinath Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Bhadrapada",
        "paksha": "Krishna",
        "tithi": 7,
        "meaning": "Conception Kalyanak of Lord Shantinath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_suparshvanath_ji___conception_kalyanak_6_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Suparshvanath Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Bhadrapada",
        "paksha": "Shukla",
        "tithi": 6,
        "meaning": "Conception Kalyanak of Lord Suparshvanath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_pushpadanta_ji___liberation_kalyanak_8_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Pushpadanta (Suvidhinath) Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Bhadrapada",
        "paksha": "Shukla",
        "tithi": 8,
        "meaning": "Liberation Kalyanak of Lord Pushpadanta (Suvidhinath)",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_vasupujya_ji___liberation_kalyanak_14_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Vasupujya Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Bhadrapada",
        "paksha": "Shukla",
        "tithi": 14,
        "meaning": "Liberation Kalyanak of Lord Vasupujya",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_naminath_ji___conception_kalyanak_2_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Naminath Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashwin",
        "paksha": "Krishna",
        "tithi": 2,
        "meaning": "Conception Kalyanak of Lord Naminath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_neminath_ji___omniscience_kalyanak_1_vrindavan_uttarapurana",
        "name": "Shri Neminath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashwin",
        "paksha": "Shukla",
        "tithi": 1,
        "meaning": "Omniscience Kalyanak of Lord Neminath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana"],
    },
    {
        "id": "shri_neminath_ji___omniscience_kalyanak_9_ashadhara",
        "name": "Shri Neminath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashwin",
        "paksha": "Shukla",
        "tithi": 9,
        "meaning": "Omniscience Kalyanak of Lord Neminath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Ashadhara"],
    },
    {
        "id": "shri_sheetalnath_ji___liberation_kalyanak_8_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Sheetalnath Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashwin",
        "paksha": "Shukla",
        "tithi": 8,
        "meaning": "Liberation Kalyanak of Lord Sheetalnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_anantnath_ji___conception_kalyanak_1_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Anantnath Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Kartika",
        "paksha": "Krishna",
        "tithi": 1,
        "meaning": "Conception Kalyanak of Lord Anantnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_sambhavnath_ji___omniscience_kalyanak_4_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Sambhavnath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Kartika",
        "paksha": "Krishna",
        "tithi": 4,
        "meaning": "Omniscience Kalyanak of Lord Sambhavnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_padmaprabha_ji___austerity_kalyanak_13_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Padmaprabha Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Kartika",
        "paksha": "Krishna",
        "tithi": 13,
        "meaning": "Austerity Kalyanak of Lord Padmaprabha",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_padmaprabha_ji___birth_kalyanak_13_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Padmaprabha Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Kartika",
        "paksha": "Krishna",
        "tithi": 13,
        "meaning": "Birth Kalyanak of Lord Padmaprabha",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_mahavira_ji___liberation_kalyanak_15_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Mahavira Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Kartika",
        "paksha": "Krishna",
        "tithi": 15,
        "meaning": "Liberation Kalyanak of Lord Mahavira",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_pushpadanta_ji___omniscience_kalyanak_2_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Pushpadanta (Suvidhinath) Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Kartika",
        "paksha": "Shukla",
        "tithi": 2,
        "meaning": "Omniscience Kalyanak of Lord Pushpadanta (Suvidhinath)",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_neminath_ji___conception_kalyanak_6_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Neminath Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Kartika",
        "paksha": "Shukla",
        "tithi": 6,
        "meaning": "Conception Kalyanak of Lord Neminath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_arahnath_ji___omniscience_kalyanak_12_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Arahnath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Kartika",
        "paksha": "Shukla",
        "tithi": 12,
        "meaning": "Omniscience Kalyanak of Lord Arahnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_sambhavnath_ji___birth_kalyanak_15_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Sambhavnath Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Kartika",
        "paksha": "Shukla",
        "tithi": 15,
        "meaning": "Birth Kalyanak of Lord Sambhavnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_mahavira_ji___austerity_kalyanak_10_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Mahavira Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Krishna",
        "tithi": 10,
        "meaning": "Austerity Kalyanak of Lord Mahavira",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_pushpadanta_ji___austerity_kalyanak_1_vrindavan_uttarapurana",
        "name": "Shri Pushpadanta (Suvidhinath) Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Shukla",
        "tithi": 1,
        "meaning": "Austerity Kalyanak of Lord Pushpadanta (Suvidhinath)",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana"],
    },
    {
        "id": "shri_pushpadanta_ji___austerity_kalyanak_9_ashadhara",
        "name": "Shri Pushpadanta (Suvidhinath) Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Shukla",
        "tithi": 9,
        "meaning": "Austerity Kalyanak of Lord Pushpadanta (Suvidhinath)",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Ashadhara"],
    },
    {
        "id": "shri_pushpadanta_ji___birth_kalyanak_1_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Pushpadanta (Suvidhinath) Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Shukla",
        "tithi": 1,
        "meaning": "Birth Kalyanak of Lord Pushpadanta (Suvidhinath)",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_arahnath_ji___austerity_kalyanak_10_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Arahnath Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Shukla",
        "tithi": 10,
        "meaning": "Austerity Kalyanak of Lord Arahnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_naminath_ji___omniscience_kalyanak_10_vrindavan",
        "name": "Shri Naminath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Shukla",
        "tithi": 10,
        "meaning": "Omniscience Kalyanak of Lord Naminath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan"],
    },
    {
        "id": "shri_naminath_ji___omniscience_kalyanak_11_uttarapurana_ashadhara",
        "name": "Shri Naminath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Shukla",
        "tithi": 11,
        "meaning": "Omniscience Kalyanak of Lord Naminath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_mallinath_ji___austerity_kalyanak_11_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Mallinath Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Shukla",
        "tithi": 11,
        "meaning": "Austerity Kalyanak of Lord Mallinath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_mallinath_ji___birth_kalyanak_11_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Mallinath Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Shukla",
        "tithi": 11,
        "meaning": "Birth Kalyanak of Lord Mallinath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_arahnath_ji___birth_kalyanak_14_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Arahnath Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Shukla",
        "tithi": 14,
        "meaning": "Birth Kalyanak of Lord Arahnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_sambhavnath_ji___austerity_kalyanak_15_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Sambhavnath Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Shukla",
        "tithi": 15,
        "meaning": "Austerity Kalyanak of Lord Sambhavnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_mallinath_ji___omniscience_kalyanak_2_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Mallinath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Krishna",
        "tithi": 2,
        "meaning": "Omniscience Kalyanak of Lord Mallinath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_chandraprabha_ji___austerity_kalyanak_11_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Chandraprabha Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Krishna",
        "tithi": 11,
        "meaning": "Austerity Kalyanak of Lord Chandraprabha",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_chandraprabha_ji___birth_kalyanak_11_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Chandraprabha Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Krishna",
        "tithi": 11,
        "meaning": "Birth Kalyanak of Lord Chandraprabha",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_parshvanath_ji___austerity_kalyanak_11_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Parshvanath Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Krishna",
        "tithi": 11,
        "meaning": "Austerity Kalyanak of Lord Parshvanath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_parshvanath_ji___birth_kalyanak_11_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Parshvanath Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Krishna",
        "tithi": 11,
        "meaning": "Birth Kalyanak of Lord Parshvanath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_sheetalnath_ji___omniscience_kalyanak_14_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Sheetalnath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Krishna",
        "tithi": 14,
        "meaning": "Omniscience Kalyanak of Lord Sheetalnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_shantinath_ji___omniscience_kalyanak_10_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Shantinath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Shukla",
        "tithi": 10,
        "meaning": "Omniscience Kalyanak of Lord Shantinath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_ajitnath_ji___omniscience_kalyanak_11_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Ajitnath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Shukla",
        "tithi": 11,
        "meaning": "Omniscience Kalyanak of Lord Ajitnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_abhinandan_ji___omniscience_kalyanak_14_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Abhinandan Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Shukla",
        "tithi": 14,
        "meaning": "Omniscience Kalyanak of Lord Abhinandan",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_dharmanath_ji___omniscience_kalyanak_15_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Dharmanath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Shukla",
        "tithi": 15,
        "meaning": "Omniscience Kalyanak of Lord Dharmanath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_padmaprabha_ji___conception_kalyanak_6_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Padmaprabha Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Krishna",
        "tithi": 6,
        "meaning": "Conception Kalyanak of Lord Padmaprabha",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_sheetalnath_ji___austerity_kalyanak_12_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Sheetalnath Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Krishna",
        "tithi": 12,
        "meaning": "Austerity Kalyanak of Lord Sheetalnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_sheetalnath_ji___birth_kalyanak_12_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Sheetalnath Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Krishna",
        "tithi": 12,
        "meaning": "Birth Kalyanak of Lord Sheetalnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_rishabhdev_ji___liberation_kalyanak_14_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Rishabhdev (Adinath) Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Krishna",
        "tithi": 14,
        "meaning": "Liberation Kalyanak of Lord Rishabhdev (Adinath)",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_shreyansnath_ji___omniscience_kalyanak_15_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Shreyansnath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Krishna",
        "tithi": 15,
        "meaning": "Omniscience Kalyanak of Lord Shreyansnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_vasupujya_ji___omniscience_kalyanak_2_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Vasupujya Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Shukla",
        "tithi": 2,
        "meaning": "Omniscience Kalyanak of Lord Vasupujya",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_vimalnath_ji___austerity_kalyanak_4_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Vimalnath Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Shukla",
        "tithi": 4,
        "meaning": "Austerity Kalyanak of Lord Vimalnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_vimalnath_ji___birth_kalyanak_4_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Vimalnath Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Shukla",
        "tithi": 4,
        "meaning": "Birth Kalyanak of Lord Vimalnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_vimalnath_ji___omniscience_kalyanak_6_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Vimalnath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Shukla",
        "tithi": 6,
        "meaning": "Omniscience Kalyanak of Lord Vimalnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_ajitnath_ji___austerity_kalyanak_10_vrindavan",
        "name": "Shri Ajitnath Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Shukla",
        "tithi": 10,
        "meaning": "Austerity Kalyanak of Lord Ajitnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan"],
    },
    {
        "id": "shri_ajitnath_ji___austerity_kalyanak_9_uttarapurana_ashadhara",
        "name": "Shri Ajitnath Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Shukla",
        "tithi": 9,
        "meaning": "Austerity Kalyanak of Lord Ajitnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_ajitnath_ji___birth_kalyanak_10_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Ajitnath Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Shukla",
        "tithi": 10,
        "meaning": "Birth Kalyanak of Lord Ajitnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_abhinandan_ji___austerity_kalyanak_12_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Abhinandan Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Shukla",
        "tithi": 12,
        "meaning": "Austerity Kalyanak of Lord Abhinandan",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_abhinandan_ji___birth_kalyanak_12_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Abhinandan Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Shukla",
        "tithi": 12,
        "meaning": "Birth Kalyanak of Lord Abhinandan",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_dharmanath_ji___austerity_kalyanak_13_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Dharmanath Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Shukla",
        "tithi": 13,
        "meaning": "Austerity Kalyanak of Lord Dharmanath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_dharmanath_ji___birth_kalyanak_13_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Dharmanath Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Shukla",
        "tithi": 13,
        "meaning": "Birth Kalyanak of Lord Dharmanath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_arahnath_ji___conception_kalyanak_2_uttarapurana",
        "name": "Shri Arahnath Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Krishna",
        "tithi": 2,
        "meaning": "Conception Kalyanak of Lord Arahnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Uttarapurana"],
    },
    {
        "id": "shri_padmaprabha_ji___liberation_kalyanak_4_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Padmaprabha Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Krishna",
        "tithi": 4,
        "meaning": "Liberation Kalyanak of Lord Padmaprabha",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_suparshvanath_ji___omniscience_kalyanak_6_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Suparshvanath Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Krishna",
        "tithi": 6,
        "meaning": "Omniscience Kalyanak of Lord Suparshvanath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_chandraprabha_ji___liberation_kalyanak_7_ashadhara",
        "name": "Shri Chandraprabha Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Krishna",
        "tithi": 7,
        "meaning": "Liberation Kalyanak of Lord Chandraprabha",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Ashadhara"],
    },
    {
        "id": "shri_chandraprabha_ji___omniscience_kalyanak_7_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Chandraprabha Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Krishna",
        "tithi": 7,
        "meaning": "Omniscience Kalyanak of Lord Chandraprabha",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_suparshvanath_ji___liberation_kalyanak_7_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Suparshvanath Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Krishna",
        "tithi": 7,
        "meaning": "Liberation Kalyanak of Lord Suparshvanath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_pushpadanta_ji___conception_kalyanak_9_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Pushpadanta (Suvidhinath) Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Krishna",
        "tithi": 9,
        "meaning": "Conception Kalyanak of Lord Pushpadanta (Suvidhinath)",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_rishabhdev_ji___omniscience_kalyanak_11_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Rishabhdev (Adinath) Ji - Omniscience Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Krishna",
        "tithi": 11,
        "meaning": "Omniscience Kalyanak of Lord Rishabhdev (Adinath)",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_shreyansnath_ji___austerity_kalyanak_11_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Shreyansnath Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Krishna",
        "tithi": 11,
        "meaning": "Austerity Kalyanak of Lord Shreyansnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_shreyansnath_ji___birth_kalyanak_11_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Shreyansnath Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Krishna",
        "tithi": 11,
        "meaning": "Birth Kalyanak of Lord Shreyansnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_munisuvrat_ji___liberation_kalyanak_12_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Munisuvrat Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Krishna",
        "tithi": 12,
        "meaning": "Liberation Kalyanak of Lord Munisuvrat",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_vasupujya_ji___austerity_kalyanak_14_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Vasupujya Ji - Austerity Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Krishna",
        "tithi": 14,
        "meaning": "Austerity Kalyanak of Lord Vasupujya",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_vasupujya_ji___birth_kalyanak_14_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Vasupujya Ji - Birth Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Krishna",
        "tithi": 14,
        "meaning": "Birth Kalyanak of Lord Vasupujya",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_arahnath_ji___conception_kalyanak_3_vrindavan_ashadhara",
        "name": "Shri Arahnath Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Shukla",
        "tithi": 3,
        "meaning": "Conception Kalyanak of Lord Arahnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Ashadhara"],
    },
    {
        "id": "shri_mallinath_ji___liberation_kalyanak_5_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Mallinath Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Shukla",
        "tithi": 5,
        "meaning": "Liberation Kalyanak of Lord Mallinath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    },
    {
        "id": "shri_chandraprabha_ji___liberation_kalyanak_7_vrindavan_uttarapurana",
        "name": "Shri Chandraprabha Ji - Liberation Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Shukla",
        "tithi": 7,
        "meaning": "Liberation Kalyanak of Lord Chandraprabha",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana"],
    },
    {
        "id": "shri_sambhavnath_ji___conception_kalyanak_8_vrindavan_uttarapurana_ashadhara",
        "name": "Shri Sambhavnath Ji - Conception Kalyanak",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Shukla",
        "tithi": 8,
        "meaning": "Conception Kalyanak of Lord Sambhavnath",
        "observance": "Special prayers, pujas, and temple visits.",
        "sources": ["Vrindavan", "Uttarapurana", "Ashadhara"],
    }
]
