FESTIVAL_REGISTRY = [
    {
        "id": "veer_shasan_jayanti__the_day_lord_mahavira_delivered_his_first_divine_sermon",
        "name": "Veer Shasan Jayanti (The day Lord Mahavira delivered his first divine sermon).",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashadha",
        "paksha": "Krishna",
        "tithi": 1
    },
    {
        "id": "shri_munisuvratnath_ji___garbh_kalyanak__conception_event",
        "name": "Shri Munisuvratnath Ji - Garbh Kalyanak (Conception event).",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashadha",
        "paksha": "Krishna",
        "tithi": 2
    },
    {
        "id": "shri_kunthunath_ji___garbh_kalyanak__conception_event",
        "name": "Shri Kunthunath Ji - Garbh Kalyanak (Conception event).",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashadha",
        "paksha": "Krishna",
        "tithi": 10
    },
    {
        "id": "shri_sumatinath_ji___garbh_kalyanak__conception_event",
        "name": "Shri Sumatinath Ji - Garbh Kalyanak (Conception event).",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Shravana",
        "paksha": "Shukla",
        "tithi": 2
    },
    {
        "id": "shri_neminath_ji___janma___tap_kalyanak__birth_and_penance_renunciation",
        "name": "Shri Neminath Ji - Janma & Tap Kalyanak (Birth and Penance/Renunciation).",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Shravana",
        "paksha": "Shukla",
        "tithi": 6
    },
    {
        "id": "shri_parshvanath_ji___moksha_kalyanak__liberation_salvation",
        "name": "Shri Parshvanath Ji - Moksha Kalyanak (Liberation/Salvation).",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Shravana",
        "paksha": "Shukla",
        "tithi": 7
    },
    {
        "id": "shri_shreyansnath_ji___moksha_kalyanak__liberation_salvation",
        "name": "Shri Shreyansnath Ji - Moksha Kalyanak (Liberation/Salvation).",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Shravana",
        "paksha": "Shukla",
        "tithi": 15
    },
    {
        "id": "shri_vasupujya_ji___kevalgyan_kalyanak__attainment_of_omniscience_enlightenment",
        "name": "Shri Vasupujya Ji - Kevalgyan Kalyanak (Attainment of Omniscience/Enlightenment).",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Shravana",
        "paksha": "Krishna",
        "tithi": 2
    },
    {
        "id": "shri_shantinath_ji___garbh_kalyanak__conception_event",
        "name": "Shri Shantinath Ji - Garbh Kalyanak (Conception event).",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Shravana",
        "paksha": "Krishna",
        "tithi": 7
    },
    {
        "id": "shri_suparshvanath_ji___garbh_kalyanak__conception_event",
        "name": "Shri Suparshvanath Ji - Garbh Kalyanak (Conception event).",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Bhadrapada",
        "paksha": "Shukla",
        "tithi": 6
    },
    {
        "id": "shri_vasupujya_ji___moksha_kalyanak__liberation_salvation",
        "name": "Shri Vasupujya Ji - Moksha Kalyanak (Liberation/Salvation).",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Bhadrapada",
        "paksha": "Shukla",
        "tithi": 14
    },
    {
        "id": "shri_naminath_ji___garbh_kalyanak__conception_event",
        "name": "Shri Naminath Ji - Garbh Kalyanak (Conception event).",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Bhadrapada",
        "paksha": "Krishna",
        "tithi": 2
    },
    {
        "id": "shri_neminath_ji___kevalgyan_kalyanak__attainment_of_omniscience_enlightenment",
        "name": "Shri Neminath Ji - Kevalgyan Kalyanak (Attainment of Omniscience/Enlightenment).",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashwin",
        "paksha": "Shukla",
        "tithi": 1
    },
    {
        "id": "shri_pushpadant_ji___moksha_kalyanak__liberation_salvation",
        "name": "Shri Pushpadant Ji - Moksha Kalyanak (Liberation/Salvation).",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashwin",
        "paksha": "Shukla",
        "tithi": 8
    },
    {
        "id": "shri_sheetalnath_ji___moksha_kalyanak__liberation_salvation",
        "name": "Shri Sheetalnath Ji - Moksha Kalyanak (Liberation/Salvation).",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashwin",
        "paksha": "Shukla",
        "tithi": 8
    },
    {
        "id": "shri_anantnath_ji___garbh_kalyanak__conception_event",
        "name": "Shri Anantnath Ji - Garbh Kalyanak (Conception event).",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashwin",
        "paksha": "Krishna",
        "tithi": 1
    },
    {
        "id": "shri_sambhavnath_ji___kevalgyan_kalyanak__attainment_of_omniscience_enlightenment",
        "name": "Shri Sambhavnath Ji - Kevalgyan Kalyanak (Attainment of Omniscience/Enlightenment).",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashwin",
        "paksha": "Krishna",
        "tithi": 4
    },
    {
        "id": "shri_mahavir_swami_ji___moksha_kalyanak__the_nirvana_liberation_of_lord_mahavira__celebrated_as_jain_diwali",
        "name": "Shri Mahavir Swami Ji - Moksha Kalyanak (The Nirvana/Liberation of Lord Mahavira, celebrated as Jain Diwali).",
        "category": "festival",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashwin",
        "paksha": "Krishna",
        "tithi": 15
    },
    {
        "id": "veer_nirvana_prapti",
        "name": "Veer Nirvana Prapti",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Kartika",
        "paksha": "Shukla",
        "tithi": 1
    },
    {
        "id": "shri_gautam_swami_gyan",
        "name": "Shri Gautam Swami Gyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Kartika",
        "paksha": "Shukla",
        "tithi": 1
    },
    {
        "id": "shri_pushpadant_ji___kevalgyan",
        "name": "Shri Pushpadant Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Kartika",
        "paksha": "Shukla",
        "tithi": 2
    },
    {
        "id": "shri_neminath_ji___garbh",
        "name": "Shri Neminath Ji - Garbh",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Kartika",
        "paksha": "Shukla",
        "tithi": 6
    },
    {
        "id": "shri_arahnath_ji___kevalgyan",
        "name": "Shri Arahnath Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Kartika",
        "paksha": "Shukla",
        "tithi": 12
    },
    {
        "id": "shri_padmaprabhu_ji___janma__tap",
        "name": "Shri Padmaprabhu Ji - Janma, Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Kartika",
        "paksha": "Shukla",
        "tithi": 13
    },
    {
        "id": "shri_sambhavnath_ji___janma",
        "name": "Shri Sambhavnath Ji - Janma",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Kartika",
        "paksha": "Shukla",
        "tithi": 15
    },
    {
        "id": "shri_mahavir_swami_ji___tap",
        "name": "Shri Mahavir Swami Ji - Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Kartika",
        "paksha": "Krishna",
        "tithi": 10
    },
    {
        "id": "shri_pushpadant_ji___janma__tap",
        "name": "Shri Pushpadant Ji - Janma, Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Shukla",
        "tithi": 1
    },
    {
        "id": "shri_mallinath_ji___janma__tap",
        "name": "Shri Mallinath Ji - Janma, Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Shukla",
        "tithi": 11
    },
    {
        "id": "shri_neminath_ji___kevalgyan",
        "name": "Shri Neminath Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Shukla",
        "tithi": 11
    },
    {
        "id": "shri_arahnath_ji___janma__tap",
        "name": "Shri Arahnath Ji - Janma, Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Shukla",
        "tithi": 14
    },
    {
        "id": "shri_sambhavnath_ji___tap",
        "name": "Shri Sambhavnath Ji - Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Shukla",
        "tithi": 15
    },
    {
        "id": "shri_mallinath_ji___kevalgyan",
        "name": "Shri Mallinath Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Krishna",
        "tithi": 2
    },
    {
        "id": "shri_chandraprabhu_ji___janma__tap",
        "name": "Shri Chandraprabhu Ji - Janma, Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Krishna",
        "tithi": 11
    },
    {
        "id": "shri_parshvanath_ji___janma__tap",
        "name": "Shri Parshvanath Ji - Janma, Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Krishna",
        "tithi": 11
    },
    {
        "id": "shri_sheetalnath_ji___kevalgyan",
        "name": "Shri Sheetalnath Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Margashirsha",
        "paksha": "Krishna",
        "tithi": 14
    },
    {
        "id": "shri_ajitnath_ji___kevalgyan",
        "name": "Shri Ajitnath Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Shukla",
        "tithi": 4
    },
    {
        "id": "shri_shantinath_ji___kevalgyan",
        "name": "Shri Shantinath Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Shukla",
        "tithi": 10
    },
    {
        "id": "shri_abhinandannath_ji___kevalgyan",
        "name": "Shri Abhinandannath Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Shukla",
        "tithi": 14
    },
    {
        "id": "shri_dharmanath_ji___kevalgyan",
        "name": "Shri Dharmanath Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Shukla",
        "tithi": 15
    },
    {
        "id": "shri_padmaprabhu_ji___garbh",
        "name": "Shri Padmaprabhu Ji - Garbh",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Krishna",
        "tithi": 6
    },
    {
        "id": "shri_sheetalnath_ji___janma__tap",
        "name": "Shri Sheetalnath Ji - Janma, Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Krishna",
        "tithi": 12
    },
    {
        "id": "shri_adinath_ji___moksha",
        "name": "Shri Adinath Ji - Moksha",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Krishna",
        "tithi": 14
    },
    {
        "id": "shri_shreyansnath_ji___kevalgyan",
        "name": "Shri Shreyansnath Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Krishna",
        "tithi": 15
    },
    {
        "id": "shri_vimalnath_ji___janma__tap",
        "name": "Shri Vimalnath Ji - Janma, Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Shukla",
        "tithi": 4
    },
    {
        "id": "shri_vimalnath_ji___kevalgyan",
        "name": "Shri Vimalnath Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Shukla",
        "tithi": 6
    },
    {
        "id": "shri_ajitnath_ji___janma__tap",
        "name": "Shri Ajitnath Ji - Janma, Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Shukla",
        "tithi": 10
    },
    {
        "id": "shri_abhinandannath_ji___janma__tap",
        "name": "Shri Abhinandannath Ji - Janma, Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Shukla",
        "tithi": 12
    },
    {
        "id": "shri_dharmanath_ji___janma__tap",
        "name": "Shri Dharmanath Ji - Janma, Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Shukla",
        "tithi": 13
    },
    {
        "id": "shri_padmaprabhu_ji___moksha",
        "name": "Shri Padmaprabhu Ji - Moksha",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Krishna",
        "tithi": 4
    },
    {
        "id": "shri_suparshvanath_ji___kevalgyan",
        "name": "Shri Suparshvanath Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Krishna",
        "tithi": 6
    },
    {
        "id": "shri_chandraprabhu_ji___kevalgyan",
        "name": "Shri Chandraprabhu Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Krishna",
        "tithi": 7
    },
    {
        "id": "shri_suparshvanath_ji___moksha",
        "name": "Shri Suparshvanath Ji - Moksha",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Krishna",
        "tithi": 7
    },
    {
        "id": "shri_pushpadant_ji___garbh",
        "name": "Shri Pushpadant Ji - Garbh",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Krishna",
        "tithi": 9
    },
    {
        "id": "shri_adinath_ji___kevalgyan",
        "name": "Shri Adinath Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Krishna",
        "tithi": 11
    },
    {
        "id": "shri_shreyansnath_ji___janma__tap",
        "name": "Shri Shreyansnath Ji - Janma, Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Krishna",
        "tithi": 11
    },
    {
        "id": "shri_munisuvratnath_ji___moksha",
        "name": "Shri Munisuvratnath Ji - Moksha",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Krishna",
        "tithi": 12
    },
    {
        "id": "shri_vasupujya_ji___janma__tap",
        "name": "Shri Vasupujya Ji - Janma, Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Magha",
        "paksha": "Krishna",
        "tithi": 14
    },
    {
        "id": "shri_arahnath_ji___garbh",
        "name": "Shri Arahnath Ji - Garbh",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Shukla",
        "tithi": 3
    },
    {
        "id": "shri_mallinath_ji___moksha",
        "name": "Shri Mallinath Ji - Moksha",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Shukla",
        "tithi": 5
    },
    {
        "id": "shri_chandraprabhu_ji___moksha",
        "name": "Shri Chandraprabhu Ji - Moksha",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Shukla",
        "tithi": 7
    },
    {
        "id": "shri_sambhavnath_ji___garbh",
        "name": "Shri Sambhavnath Ji - Garbh",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Shukla",
        "tithi": 8
    },
    {
        "id": "shri_anantnath_ji___moksha",
        "name": "Shri Anantnath Ji - Moksha",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Krishna",
        "tithi": 4
    },
    {
        "id": "shri_parshvanath_ji___kevalgyan",
        "name": "Shri Parshvanath Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Krishna",
        "tithi": 4
    },
    {
        "id": "shri_chandraprabhu_ji___garbh",
        "name": "Shri Chandraprabhu Ji - Garbh",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Krishna",
        "tithi": 5
    },
    {
        "id": "shri_sheetalnath_ji___garbh",
        "name": "Shri Sheetalnath Ji - Garbh",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Krishna",
        "tithi": 8
    },
    {
        "id": "shri_adinath_ji___janma__tap",
        "name": "Shri Adinath Ji - Janma, Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Krishna",
        "tithi": 9
    },
    {
        "id": "shri_anantnath_ji___kevalgyan",
        "name": "Shri Anantnath Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Phalguna",
        "paksha": "Krishna",
        "tithi": 15
    },
    {
        "id": "shri_mallinath_ji___garbh",
        "name": "Shri Mallinath Ji - Garbh",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 1
    },
    {
        "id": "shri_kunthunath_ji___kevalgyan",
        "name": "Shri Kunthunath Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 3
    },
    {
        "id": "shri_ajitnath_ji___moksha",
        "name": "Shri Ajitnath Ji - Moksha",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 5
    },
    {
        "id": "shri_sambhavnath_ji___moksha",
        "name": "Shri Sambhavnath Ji - Moksha",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 6
    },
    {
        "id": "shri_sumatinath_ji___janma__tap__kevalgyan__moksha",
        "name": "Shri Sumatinath Ji - Janma, Tap, Kevalgyan, Moksha",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 11
    },
    {
        "id": "shri_arahnath_ji___moksha",
        "name": "Shri Arahnath Ji - Moksha",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 11
    },
    {
        "id": "shri_mahavir_swami_ji___janma",
        "name": "Shri Mahavir Swami Ji - Janma",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 13
    },
    {
        "id": "shri_padmaprabhu_ji___kevalgyan",
        "name": "Shri Padmaprabhu Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 15
    },
    {
        "id": "shri_parshvanath_ji___garbh",
        "name": "Shri Parshvanath Ji - Garbh",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Krishna",
        "tithi": 2
    },
    {
        "id": "shri_munisuvratnath_ji___kevalgyan",
        "name": "Shri Munisuvratnath Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Krishna",
        "tithi": 9
    },
    {
        "id": "shri_munisuvratnath_ji___janma__tap",
        "name": "Shri Munisuvratnath Ji - Janma, Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Krishna",
        "tithi": 10
    },
    {
        "id": "shri_naminath_ji___moksha",
        "name": "Shri Naminath Ji - Moksha",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Krishna",
        "tithi": 14
    },
    {
        "id": "shri_kunthunath_ji___janma__tap__moksha",
        "name": "Shri Kunthunath Ji - Janma, Tap, Moksha",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Shukla",
        "tithi": 1
    },
    {
        "id": "shri_abhinandannath_ji___garbh__moksha",
        "name": "Shri Abhinandannath Ji - Garbh, Moksha",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Shukla",
        "tithi": 6
    },
    {
        "id": "shri_dharmanath_ji___garbh",
        "name": "Shri Dharmanath Ji - Garbh",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Shukla",
        "tithi": 8
    },
    {
        "id": "shri_mahavir_swami_ji___kevalgyan",
        "name": "Shri Mahavir Swami Ji - Kevalgyan",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Shukla",
        "tithi": 10
    },
    {
        "id": "shri_shreyansnath_ji___garbh",
        "name": "Shri Shreyansnath Ji - Garbh",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Krishna",
        "tithi": 8
    },
    {
        "id": "shri_vimalnath_ji___garbh",
        "name": "Shri Vimalnath Ji - Garbh",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Krishna",
        "tithi": 10
    },
    {
        "id": "shri_anantnath_ji___janma__tap",
        "name": "Shri Anantnath Ji - Janma, Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Krishna",
        "tithi": 12
    },
    {
        "id": "shri_sheetalnath_ji___janma__tap__moksha",
        "name": "Shri Sheetalnath Ji - Janma, Tap, Moksha",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Krishna",
        "tithi": 14
    },
    {
        "id": "shri_ajitnath_ji___garbh",
        "name": "Shri Ajitnath Ji - Garbh",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Krishna",
        "tithi": 15
    },
    {
        "id": "shri_dharmanath_ji___moksha",
        "name": "Shri Dharmanath Ji - Moksha",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Shukla",
        "tithi": 4
    },
    {
        "id": "shri_suparshvanath_ji___janma__tap",
        "name": "Shri Suparshvanath Ji - Janma, Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Shukla",
        "tithi": 12
    },
    {
        "id": "shri_munisuvratnath_ji___garbh",
        "name": "Shri Munisuvratnath Ji - Garbh",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Krishna",
        "tithi": 2
    },
    {
        "id": "shri_vasupujya_ji___garbh",
        "name": "Shri Vasupujya Ji - Garbh",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Krishna",
        "tithi": 6
    },
    {
        "id": "shri_vimalnath_ji___moksha",
        "name": "Shri Vimalnath Ji - Moksha",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Krishna",
        "tithi": 6
    },
    {
        "id": "shri_naminath_ji___janma__tap",
        "name": "Shri Naminath Ji - Janma, Tap",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Krishna",
        "tithi": 10
    },
    {
        "id": "shri_mahavir_swami_ji___garbh",
        "name": "Shri Mahavir Swami Ji - Garbh",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashadha",
        "paksha": "Shukla",
        "tithi": 6
    },
    {
        "id": "shri_neminath_ji___moksha",
        "name": "Shri Neminath Ji - Moksha",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashadha",
        "paksha": "Shukla",
        "tithi": 8
    },
    {
        "id": "shri_shantinath_ji_janma_tap_moksha",
        "name": "Shri Shantinath Ji - Janma, Tap, Moksha",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Vaishakha",
        "paksha": "Krishna",
        "tithi": 14
    },
    {
        "id": "mahavir_janma_kalyanak",
        "name": "Mahavir Janma Kalyanak (Mahavir Jayanti)",
        "name_hindi": "महावीर जन्म कल्याणक",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 13,
        "meaning": "Birth Anniversary of Lord Mahavira",
        "observance": "Rath Yatra and Fasting",
        "sources": ["Jain Traditions"]
    },
    {
        "id": "diwali",
        "name": "Diwali (Mahavir Nirvan & Gautam Swami Kevalgyan)",
        "name_hindi": "दीपावली (भगवान महावीर निर्वाण)",
        "category": "festival",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Kartik",
        "paksha": "Krishna",
        "tithi": 15,
        "meaning": "Moksha of Bhagwan Mahavir and Kevalgyan of Gautam Swami",
        "observance": "Laddoo offering & Swadhyay",
        "sources": ["Jain Traditions"]
    },
    {
        "id": "meru_trayodashi",
        "name": "Meru Trayodashi",
        "name_hindi": "मेरु त्रयोदशी",
        "category": "festival",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Krishna",
        "tithi": 13,
        "meaning": "Nirvan of Bhagwan Rishabhdev (Adinath)",
        "observance": "Fasting and Prayer",
        "sources": ["Jain Traditions"]
    },
    {
        "id": "parshvanath_jayanti",
        "name": "Shri Parshvanath Jayanti",
        "name_hindi": "श्री पार्श्वनाथ जयंती",
        "category": "kalyanak",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Pausha",
        "paksha": "Krishna",
        "tithi": 10,
        "meaning": "Janma Kalyanak of Bhagwan Parshvanath",
        "observance": "Pooja and Fasting",
        "sources": ["Jain Traditions"]
    },
    {
        "id": "samvatsari_tapagachchha",
        "name": "Samvatsari (Tapagachchha)",
        "name_hindi": "संवत्सरी (तपागच्छ)",
        "category": "festival",
        "profiles": ["shwetambar_murtipujak_tapagachchha"],
        "rule_type": "SingleTithi",
        "jain_month": "Bhadrapada",
        "paksha": "Shukla",
        "tithi": 4,
        "vriddhi_rule": "second_day",
        "meaning": "Samvatsari Mahaparva",
        "observance": "Kshamapana & Upvas",
        "sources": ["Tapagachchha Rules"]
    },
    {
        "id": "samvatsari_sthanakvasi",
        "name": "Samvatsari (Sthanakvasi / Terapanthi)",
        "name_hindi": "संवत्सरी (स्थानकवासी/तेरापंथी)",
        "category": "festival",
        "profiles": ["shwetambar_sthanakvasi", "shwetambar_terapanthi"],
        "rule_type": "SingleTithi",
        "jain_month": "Bhadrapada",
        "paksha": "Shukla",
        "tithi": 5,
        "vriddhi_rule": "second_day",
        "meaning": "Samvatsari Mahaparva",
        "observance": "Kshamapana & Upvas",
        "sources": ["Sthanakvasi Rules"]
    },
    {
        "id": "parva_tithi_amavasya",
        "name": "Parva Tithi - Amavasya",
        "name_hindi": "अमावस्या पर्व तिथि",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": None,
        "paksha": "Krishna",
        "tithi": 15,
        "meaning": "Monthly Amavasya Parva Tithi",
        "observance": "Special prayer and self-study",
        "sources": ["Jain Panchang Rules"]
    },
    {
        "id": "parva_tithi_purnima",
        "name": "Parva Tithi - Purnima",
        "name_hindi": "पूर्णिमा पर्व तिथि",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": None,
        "paksha": "Shukla",
        "tithi": 15,
        "meaning": "Monthly Purnima Parva Tithi",
        "observance": "Special prayer and self-study",
        "sources": ["Jain Panchang Rules"]
    },
    {
        "id": "parva_tithi_ashtami_krishna",
        "name": "Parva Tithi - Krishna Ashtami",
        "name_hindi": "कृष्ण अष्टमी पर्व तिथि",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": None,
        "paksha": "Krishna",
        "tithi": 8,
        "meaning": "Monthly Krishna Ashtami Parva Tithi",
        "observance": "Fasting / Swadhyay",
        "sources": ["Jain Panchang Rules"]
    },
    {
        "id": "parva_tithi_ashtami_shukla",
        "name": "Parva Tithi - Shukla Ashtami",
        "name_hindi": "शुक्ल अष्टमी पर्व तिथि",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": None,
        "paksha": "Shukla",
        "tithi": 8,
        "meaning": "Monthly Shukla Ashtami Parva Tithi",
        "observance": "Fasting / Swadhyay",
        "sources": ["Jain Panchang Rules"]
    },
    {
        "id": "pakhi_chaudas_ashadha",
        "name": "Pakhi Chaudas - Shukla Chaturdashi",
        "name_hindi": "पाखी चौदस (शुक्ल चतुर्दशी)",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashadha",
        "paksha": "Shukla",
        "tithi": 14,
        "meaning": "Chaturmas Pakhi Chaudas",
        "observance": "Pakshik Pratikraman",
        "sources": ["Jain Panchang Rules"]
    },
    {
        "id": "pakhi_chaudas_shravana",
        "name": "Pakhi Chaudas - Shukla Chaturdashi",
        "name_hindi": "पाखी चौदस (शुक्ल चतुर्दशी)",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Shravana",
        "paksha": "Shukla",
        "tithi": 14,
        "meaning": "Chaturmas Pakhi Chaudas",
        "observance": "Pakshik Pratikraman",
        "sources": ["Jain Panchang Rules"]
    },
    {
        "id": "pakhi_chaudas_bhadrapada",
        "name": "Pakhi Chaudas - Shukla Chaturdashi",
        "name_hindi": "पाखी चौदस (शुक्ल चतुर्दशी)",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Bhadrapada",
        "paksha": "Shukla",
        "tithi": 14,
        "meaning": "Chaturmas Pakhi Chaudas",
        "observance": "Pakshik Pratikraman",
        "sources": ["Jain Panchang Rules"]
    },
    {
        "id": "pakhi_chaudas_ashwin",
        "name": "Pakhi Chaudas - Shukla Chaturdashi",
        "name_hindi": "पाखी चौदस (शुक्ल चतुर्दशी)",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashwin",
        "paksha": "Shukla",
        "tithi": 14,
        "meaning": "Chaturmas Pakhi Chaudas",
        "observance": "Pakshik Pratikraman",
        "sources": ["Jain Panchang Rules"]
    },
    {
        "id": "jyeshtha_jinvar_vrat_begins",
        "name": "Jyeshtha Jinvar Vrat Begins",
        "name_hindi": "ज्येष्ठ जिनवर व्रत प्रारंभ",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Krishna",
        "tithi": 1,
        "meaning": "Start of Jyeshtha Jinvar Vrat",
        "observance": "Fasting and worship",
        "sources": ["Jain Panchang Rules"]
    },
    {
        "id": "shrut_panchami",
        "name": "Shrut Panchami (Jinvani Divas)",
        "name_hindi": "श्रुत पंचमी (जिनवाणी दिवस)",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Jyeshtha",
        "paksha": "Shukla",
        "tithi": 5,
        "meaning": "Worship of the first written Jain scriptures",
        "observance": "Jinvani Puja, Swadhyay",
        "sources": ["Jain Panchang Rules"]
    },
    {
        "id": "veera_shasana_jayanti",
        "name": "Veera Shasana Jayanti",
        "name_hindi": "वीर शासन जयंती",
        "category": "parva",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashadha",
        "paksha": "Krishna",
        "tithi": 1,
        "meaning": "Commemorates Lord Mahavira's first divine sermon (Divya Dhwani)",
        "observance": "Worship, discourses, and celebration",
        "sources": ["Jain Panchang Rules"]
    },
    {
        "id": "raksha_bandhan",
        "name": "Raksha Bandhan (Vishnukumar Muni Parv)",
        "name_hindi": "रक्षाबंधन (विष्णुकुमार मुनि पर्व)",
        "category": "mahaparv",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Shravana",
        "paksha": "Shukla",
        "tithi": 15,
        "meaning": "Commemorates Muni Vishnukumar protecting 700 Jain ascetics",
        "observance": "Worship, community gathering",
        "sources": ["Jain Panchang Rules"]
    },
    {
        "id": "navpad_ayambil_oli_autumn",
        "name": "Oli Fasting Begins (Navpad Ayambil Oli)",
        "name_hindi": "ओली प्रारंभ (नवपद आयम्बिल ओली)",
        "category": "mahaparv",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashwin",
        "paksha": "Shukla",
        "tithi": 15,
        "meaning": "Beginning of the 9-day Autumn Navpad Ayambil Oli fast.",
        "observance": "Ayambil fast for 9 days, meditating on the Navpad.",
        "sources": ["Jain Panchang Rules"]
    },
    {
        "id": "mahavir_nirvana_deepavali",
        "name": "Mahavir Swami Nirvana Kalyanak (Deepavali)",
        "name_hindi": "महावीर स्वामी निर्वाण कल्याणक (दीपावली)",
        "category": "mahaparv",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Ashwin",
        "paksha": "Krishna",
        "tithi": 15,
        "meaning": "Bhagwan Mahavira attained Nirvana (liberation) at Pavapuri.",
        "observance": "Lighting of lamps, offering of Nirvan Ladoo.",
        "sources": ["Jain Panchang Rules"]
    },
    {
        "id": "navpad_ayambil_oli_spring",
        "name": "Oli Fasting Begins (Navpad Ayambil Oli)",
        "name_hindi": "ओली प्रारंभ (नवपद आयम्बिल ओली)",
        "category": "mahaparv",
        "profiles": ["all"],
        "rule_type": "SingleTithi",
        "jain_month": "Chaitra",
        "paksha": "Shukla",
        "tithi": 9,
        "meaning": "Beginning of the 9-day Spring Navpad Ayambil Oli fast.",
        "observance": "Ayambil fast for 9 days, meditating on the Navpad.",
        "sources": ["Jain Panchang Rules"]
    }
]
