package com.example.jainpanchang.domain

data class FestivalRule(
    val id: String,
    val name: String,
    val nameHindi: String,
    val category: String,
    val profiles: List<String>,
    val jainMonth: String?, // Can be null for parva tithis
    val paksha: String,
    val tithi: String, // String to support ranges like "7-15" and integers
    val vriddhiRule: String,
    val kshayaRule: String,
    val adhikaRule: String,
    val meaning: String,
    val observance: String,
    val sources: List<String>
)

object JainFestivalRules {
    val FESTIVAL_REGISTRY = listOf(
        FestivalRule(
            id = "mahavir_janma_kalyanak",
            name = "Mahavir Janma Kalyanak",
            nameHindi = "महावीर जन्म कल्याणक",
            category = "kalyanak",
            profiles = listOf("shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"),
            jainMonth = "Chaitra",
            paksha = "Shukla",
            tithi = "13",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "The birthday of Lord Mahavir, the 24th Tirthankara",
            observance = "Pujas, reading the Kalpa Sutra, and fasts. Non-Murtipujaks focus on meditation.",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        ),
        FestivalRule(
            id = "samvatsari_tapagachchha",
            name = "Samvatsari (Tapagachchha)",
            nameHindi = "संवत्सरी (तपगच्छ)",
            category = "festival",
            profiles = listOf("shwetambar_murtipujak_tapagachchha"),
            jainMonth = "Bhadrapada",
            paksha = "Shukla",
            tithi = "4",
            vriddhiRule = "second_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "The final day of Paryushan, the day of universal forgiveness",
            observance = "Performance of Samvatsari Pratikramana, seek forgiveness with 'Micchami Dukkadam'",
            sources = listOf("https://www.jainfoundation.in/JAINLIBRARY/books/Historical_Perspective_of_Samvatsari_Day_and_Jain_Calendar_200022_data.pdf")
        ),
        FestivalRule(
            id = "samvatsari_sthanakvasi",
            name = "Samvatsari (Sthanakvasi)",
            nameHindi = "संवत्सरी (स्थानकवासी)",
            category = "festival",
            profiles = listOf("shwetambar_sthanakvasi"),
            jainMonth = "Bhadrapada",
            paksha = "Shukla",
            tithi = "5",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "The final day of Paryushan for Sthanakvasis, the day of universal forgiveness",
            observance = "Meditation, chanting, Pratikramana, and 'Micchami Dukkadam'",
            sources = listOf("https://www.jainfoundation.in/JAINLIBRARY/books/Historical_Perspective_of_Samvatsari_Day_and_Jain_Calendar_200022_data.pdf")
        ),
        FestivalRule(
            id = "samvatsari_terapanthi",
            name = "Samvatsari (Terapanthi)",
            nameHindi = "संवत्सरी (तेरापंथी)",
            category = "festival",
            profiles = listOf("shwetambar_terapanthi"),
            jainMonth = "Bhadrapada",
            paksha = "Shukla",
            tithi = "5",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "The final day of Paryushan for Terapanthis, the day of universal forgiveness",
            observance = "Strictly non-ritualistic meditation, fasts, and Samvatsari Pratikramana",
            sources = listOf("https://www.jainfoundation.in/JAINLIBRARY/books/Historical_Perspective_of_Samvatsari_Day_and_Jain_Calendar_200022_data.pdf")
        ),
        FestivalRule(
            id = "paryushan_start_tapagachchha",
            name = "Paryushan Start (Tapagachchha)",
            nameHindi = "पर्युषण प्रारंभ (तपगच्छ)",
            category = "festival",
            profiles = listOf("shwetambar_murtipujak_tapagachchha"),
            jainMonth = "Bhadrapada",
            paksha = "Krishna",
            tithi = "12",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "Start of the 8-day Paryushan festival of self-purification",
            observance = "Daily reading of the Kalpa Sutra, listening to discourses, and fasting",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        ),
        FestivalRule(
            id = "paryushan_start_sthanakvasi",
            name = "Paryushan Start (Sthanakvasi)",
            nameHindi = "पर्युषण प्रारंभ (स्थानकवासी)",
            category = "festival",
            profiles = listOf("shwetambar_sthanakvasi"),
            jainMonth = "Bhadrapada",
            paksha = "Krishna",
            tithi = "13",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "Start of the 8-day Paryushan festival",
            observance = "Spiritual discourses, meditation, fasting, and reading of scriptures",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        ),
        FestivalRule(
            id = "paryushan_start_terapanthi",
            name = "Paryushan Start (Terapanthi)",
            nameHindi = "पर्युषण प्रारंभ (तेरापंथी)",
            category = "festival",
            profiles = listOf("shwetambar_terapanthi"),
            jainMonth = "Bhadrapada",
            paksha = "Krishna",
            tithi = "13",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "Start of the 8-day Paryushan festival",
            observance = "Scriptural contemplation, fasting, and strict vows",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        ),
        FestivalRule(
            id = "ayambil_oli_chaitra",
            name = "Chaitra Ayambil Oli",
            nameHindi = "चैत्री आयंबिल ओली",
            category = "fast",
            profiles = listOf("shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"),
            jainMonth = "Chaitra",
            paksha = "Shukla",
            tithi = "7-15",
            vriddhiRule = "all_days",
            kshayaRule = "adjust_9_days",
            adhikaRule = "nija_only",
            meaning = "A 9-day festival of Ayambil fasts honoring the Navpad",
            observance = "Eating only once a day of boiled grains/cereals without spice, oil, ghee, milk, or curd",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/ayambil-oli/")
        ),
        FestivalRule(
            id = "ayambil_oli_ashvin",
            name = "Ashvin Ayambil Oli",
            nameHindi = "आसोज आयंबिल ओली",
            category = "fast",
            profiles = listOf("shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"),
            jainMonth = "Ashwin",
            paksha = "Shukla",
            tithi = "7-15",
            vriddhiRule = "all_days",
            kshayaRule = "adjust_9_days",
            adhikaRule = "nija_only",
            meaning = "A 9-day festival of Ayambil fasts honoring the Navpad",
            observance = "Fasting on boiled grains, performing pujas (Murtipujak) or meditation",
            sources = listOf("https://www.msjs.org.au/resources/library/knowledge-base/festivals/navpadji-oli/")
        ),
        FestivalRule(
            id = "diwali",
            name = "Diwali",
            nameHindi = "दिवाली",
            category = "festival",
            profiles = listOf("shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"),
            jainMonth = "Kartika",
            paksha = "Krishna",
            tithi = "15",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "Lord Mahavir's Nirvana (Moksha) Kalyanak",
            observance = "Lighting lamps, fasting, chanting prayers",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        ),
        FestivalRule(
            id = "jain_new_year",
            name = "Jain New Year",
            nameHindi = "नूतन वर्ष (वीर निर्वाण संवत)",
            category = "festival",
            profiles = listOf("shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"),
            jainMonth = "Kartika",
            paksha = "Shukla",
            tithi = "1",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "Gautam Swami's Kevalgyan Kalyanak, start of VNS year",
            observance = "Visiting temples, greeting with 'Saal Mubarak', listening to Gautam Swami's Ras",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        ),
        FestivalRule(
            id = "jnan_panchami",
            name = "Jnan Panchami",
            nameHindi = "ज्ञान पंचमी",
            category = "festival",
            profiles = listOf("shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"),
            jainMonth = "Kartika",
            paksha = "Shukla",
            tithi = "5",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "Day of worshipping knowledge and scriptures",
            observance = "Fasting, cleaning and worshipping religious books, performing Jnan Puja",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        ),
        FestivalRule(
            id = "dev_diwali",
            name = "Dev Diwali",
            nameHindi = "देव दिवाली",
            category = "festival",
            profiles = listOf("shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"),
            jainMonth = "Kartika",
            paksha = "Shukla",
            tithi = "15",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "Culmination of Kartiki Chaturmas, reopening of Shatrunjay hills",
            observance = "Illuminating temples, organizing grand pujas, and resuming pilgrimage",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        ),
        FestivalRule(
            id = "maun_ekadashi",
            name = "Maun Agyaras",
            nameHindi = "मौन ग्यारस",
            category = "festival",
            profiles = listOf("shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"),
            jainMonth = "Margashirsha",
            paksha = "Shukla",
            tithi = "11",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "Day honoring five Kalyanakas of various Tirthankaras",
            observance = "Maintaining complete silence (Maun), performing 150 logassa, fasting",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        ),
        FestivalRule(
            id = "parshvanath_jayanti",
            name = "Paush Dashami",
            nameHindi = "पोष दशमी",
            category = "festival",
            profiles = listOf("shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"),
            jainMonth = "Pausha",
            paksha = "Krishna",
            tithi = "10",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "Birthday Kalyanak of Lord Parshvanath (23rd Tirthankara)",
            observance = "Fasting, performing Paush Dashami Pujas, chanting Parshvanath prayers",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        ),
        FestivalRule(
            id = "meru_trayodashi",
            name = "Meru Trayodashi",
            nameHindi = "मेरु त्रयोदशी",
            category = "festival",
            profiles = listOf("shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"),
            jainMonth = "Magha",
            paksha = "Krishna",
            tithi = "13",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "Lord Rishabhdev's (Adinath) Nirvana Kalyanak",
            observance = "Worship of Mount Shatrunjay, specialized pujas and fasts",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        ),
        FestivalRule(
            id = "chaumasi_chaudas_ashadha",
            name = "Ashadha Chaumasi Chaudas",
            nameHindi = "आषाढी चौमासी चौदश",
            category = "festival",
            profiles = listOf("shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"),
            jainMonth = "Ashadha",
            paksha = "Shukla",
            tithi = "14",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "Start of the holy Chaturmas period",
            observance = "Fasting, starting Chaturmas vows, and performing special Pratikramana",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        ),
        FestivalRule(
            id = "chaumasi_chaudas_kartika",
            name = "Kartika Chaumasi Chaudas",
            nameHindi = "कार्तिकी चौमासी चौदश",
            category = "festival",
            profiles = listOf("shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"),
            jainMonth = "Kartika",
            paksha = "Shukla",
            tithi = "14",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "End of the main Chaturmas period",
            observance = "Performing grand Chaumasi Pratikramana, concluding monsoon vows",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        ),
        FestivalRule(
            id = "chaumasi_chaudas_phalguna",
            name = "Phalguna Chaumasi Chaudas",
            nameHindi = "फाल्गुनी चौमासी चौदश",
            category = "festival",
            profiles = listOf("shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"),
            jainMonth = "Phalguna",
            paksha = "Shukla",
            tithi = "14",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "Third Chaumasi Chaudas of the year",
            observance = "Spiritual cleansing, fasting, and performing Chaumasi Pratikramana",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        ),
        FestivalRule(
            id = "pakhi_chaudas_shukla",
            name = "Pakhi Chaudas (Shukla)",
            nameHindi = "पाखी चौदश (शुक्ल)",
            category = "parva",
            profiles = listOf("shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"),
            jainMonth = null,
            paksha = "Shukla",
            tithi = "14",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "Bi-weekly day of spiritual purification and fasting",
            observance = "Performance of Pakshik Pratikramana and observing dietary restrictions",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        ),
        FestivalRule(
            id = "pakhi_chaudas_krishna",
            name = "Pakhi Chaudas (Krishna)",
            nameHindi = "पाखी चौदश (कृष्ण)",
            category = "parva",
            profiles = listOf("shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"),
            jainMonth = null,
            paksha = "Krishna",
            tithi = "14",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "Bi-weekly day of spiritual purification and fasting",
            observance = "Performance of Pakshik Pratikramana and observing dietary restrictions",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        ),
        FestivalRule(
            id = "parva_tithi_ashtami_shukla",
            name = "Parva Tithi (Shukla Ashtami)",
            nameHindi = "पर्व तिथि (शुक्ल अष्टमी)",
            category = "parva",
            profiles = listOf("shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"),
            jainMonth = null,
            paksha = "Shukla",
            tithi = "8",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "Fortnightly holy day for fasting and penance",
            observance = "Observing abstinences, avoiding green vegetables, performing Samayik",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        ),
        FestivalRule(
            id = "parva_tithi_ashtami_krishna",
            name = "Parva Tithi (Krishna Ashtami)",
            nameHindi = "पर्व तिथि (कृष्ण अष्टमी)",
            category = "parva",
            profiles = listOf("shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"),
            jainMonth = null,
            paksha = "Krishna",
            tithi = "8",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "Fortnightly holy day for fasting and penance",
            observance = "Avoiding green/root vegetables, engaging in scripture study",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        ),
        FestivalRule(
            id = "parva_tithi_purnima",
            name = "Parva Tithi (Purnima)",
            nameHindi = "पर्व तिथि (पूर्णिमा)",
            category = "parva",
            profiles = listOf("shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"),
            jainMonth = null,
            paksha = "Shukla",
            tithi = "15",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "Monthly full moon spiritual day",
            observance = "Temple visits, special prayers, and charitable donations",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        ),
        FestivalRule(
            id = "parva_tithi_amavasya",
            name = "Parva Tithi (Amavasya)",
            nameHindi = "पर्व तिथि (अमावस्या)",
            category = "parva",
            profiles = listOf("shwetambar_murtipujak_tapagachchha", "shwetambar_sthanakvasi", "shwetambar_terapanthi"),
            jainMonth = null,
            paksha = "Krishna",
            tithi = "15",
            vriddhiRule = "first_day",
            kshayaRule = "next_day",
            adhikaRule = "nija_only",
            meaning = "Monthly new moon spiritual day",
            observance = "Inner contemplation, fasting, and offering prayers",
            sources = listOf("https://jainpedia.org/themes/practices/festivals/")
        )
    )
}
